allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 0
  cipher: auto
  name: 加拿大-1
  network: ws
  port: 443
  server: 23.162.200.227
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  ws-opts:
    path: /linkvws
- alterId: 64
  cipher: auto
  name: 中国-1
  network: tcp
  port: 40002
  server: 183.236.48.163
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 中国-2
  network: tcp
  port: 46665
  server: 120.237.79.157
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 3ac820af-becb-45d7-9e7a-e33d02961bb3
- alterId: 0
  cipher: auto
  name: 中国-3
  network: ws
  port: 33202
  server: yd2.ainivp.com
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 9204afcd-023e-781f-1abc-c12efccd1344
  ws-opts:
    headers:
      Host: yd2.ainivp.com
    path: /ray
- alterId: 64
  cipher: auto
  name: 中国-4
  network: tcp
  port: 34565
  server: 120.232.153.71
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: 西班牙-1
  network: ws
  password: bpb-trojan
  port: 443
  server: 185.238.228.6
  skip-cert-verify: true
  sni: 403b3611-99bc-43b7-88D7-26Ed5D0825a9-3.PAgeS.dEv
  type: trojan
  ws-opts:
    headers:
      Host: 403b3611-99bc-43b7-88D7-26Ed5D0825a9-3.PAgeS.dEv
    path: /trLb1imnrxPEhfzfwk
- cipher: aes-128-gcm
  name: 美国-1
  password: shadowsocks
  port: 443
  server: 212.102.47.131
  type: ss
- client-fingerprint: random
  name: 香港-1
  network: ws
  port: 23555
  server: 219.77.65.212
  servername: juzi8186.5112233.xyz
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: f775978b-6e22-41a8-ae5e-5f9779e6745f
  ws-opts:
    headers:
      Host: juzi8186.5112233.xyz
    path: /?ed=2560
- name: 爱尔兰-1
  network: ws
  port: 22222
  server: 34.251.229.14
  servername: telegram-channel-vlessconfig.sohala.uk
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: 05519058-d2ac-4f28-9e4a-2b2a1386749e
  ws-opts:
    headers:
      Host: telegram-channel-vlessconfig.sohala.uk
    path: /telegram-channel-vlessconfig-ws
- alterId: 0
  cipher: auto
  name: 伊朗-1
  network: tcp
  port: 443
  server: 185.231.181.46
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 95a69849-23c4-4669-91ed-cec32ad1341c
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-1
  network: ws
  port: 8080
  server: m003.mmzhk.website
  servername: m003.mmzhk.website
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 6dde3b3f-0a00-448a-a406-26d0960d1655
  ws-opts:
    headers:
      Host: daohang.mmzhk.website
    path: /xyz
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-2
  network: ws
  port: 8080
  server: m003.mmzhk.website
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: c3d1b53d-8cbe-4455-a009-bfa08e55f11d
  ws-opts:
    headers:
      Host: daohang.mmzhk.website
    path: /xyz
- name: 俄罗斯联邦-3
  network: ws
  password: bpb-trojan
  port: 2096
  server: 45.142.120.4
  skip-cert-verify: true
  sni: 403B3611-99bC-43b7-88D7-26ed5d0825A9-3.PageS.DEV
  type: trojan
  ws-opts:
    headers:
      Host: 403B3611-99bC-43b7-88D7-26ed5d0825A9-3.PageS.DEV
    path: /troUbg9Q3QgD0TJRfy
- name: 美国-2
  network: ws
  port: 8880
  server: 104.19.209.229
  type: vless
  udp: true
  uuid: f0d584bc-342f-4443-ba24-79e4d0e504b1
  ws-opts:
    headers:
      Host: late-tooth.granzinhannah.workers.dev
    path: /?ed=2560
- name: 美国-3
  network: ws
  port: 80
  server: 167.82.30.71
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: samane.ir
    path: /4u7lAS4nPLtz0xPz?ed=2560
- name: 美国-4
  network: ws
  port: 8880
  server: 104.20.19.168
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: f0d584bc-342f-4443-ba24-79e4d0e504b1
  ws-opts:
    headers:
      Host: late-tooth.granzinhannah.workers.dev
    path: /?ed=2048
- name: 美国-5
  network: ws
  port: 8880
  server: 104.20.71.132
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: f0d584bc-342f-4443-ba24-79e4d0e504b1
  ws-opts:
    headers:
      Host: late-tooth.granzinhannah.workers.dev
    path: /Telegram@Linkvws?ed=2560
- cipher: aes-128-gcm
  name: 美国-6
  password: shadowsocks
  port: 443
  server: 156.146.38.168
  type: ss
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: 美国-7
  network: ws
  port: 443
  server: 199.232.5.101
  servername: mefa.ir
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: mefa.ir
    path: /H?ed=2560
- name: 美国-8
  network: ws
  port: 80
  server: 199.232.37.15
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560
- cipher: aes-256-gcm
  name: 美国-9
  password: faBAoD54k87UJG7
  port: 2376
  server: 38.75.136.117
  type: ss
- name: 美国-10
  network: ws
  port: 80
  server: 199.232.37.15
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560
- cipher: aes-256-gcm
  name: 美国-11
  password: Y6R9pAtvxxzmGC
  port: 3389
  server: 23.134.94.168
  type: ss
- name: 美国-12
  network: ws
  port: 2095
  server: www.speedtest.net
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: a70e1ca7-0cfa-5d07-b068-ca7657f9aba8
  ws-opts:
    headers:
      Host: www.digikala.com.joinTelegram.mosiv2.fi3.vless.Sitespeedtest.net.
    path: /join-@mosiv2-@mosiv2-?ed=2048
- name: 美国-13
  network: ws
  port: 2052
  server: www.speedtest.net
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: bd51708b-07de-561f-9053-d2e90ca4ee20
  ws-opts:
    headers:
      Host: www.digikala.com.joinTelegram.mosiv2.pl1.vless.Sitespeedtest.net.
    path: /join-@mosiv2-@mosiv2-?ed=2048
- name: 美国-14
  network: ws
  port: 80
  server: 151.101.2.165
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 4639cda7-0742-4bcd-ab1e-b7c879c2189c
  ws-opts:
    headers:
      Host: que4.ir
    path: /v2pedia?ed=2048
- client-fingerprint: chrome
  name: 美国-15
  network: ws
  port: 443
  server: 151.101.130.228
  servername: hajlab.ucdavis.edu
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: 6407d901-f9d0-4e14-b805-39cd7440bf63
  ws-opts:
    headers:
      Host: Join_Evay_vpn.ir
    path: /@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn?ed=2560
- name: 美国-16
  network: ws
  port: 443
  server: 198.41.209.2
  servername: meta1.modinso.ir
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: 11d876aa-6818-4d0d-9f5b-2c7e8c5499c8
  ws-opts:
    headers:
      Host: meta1.modinso.ir
    path: /@metavpnn
- alpn:
  - http/1.1
  alterId: 0
  cipher: auto
  name: 美国-17
  network: ws
  port: 443
  server: www.baldengineer.com
  servername: yen63jj36j3jfflan.thelastronin.cloudns.org
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: f584de15-2034-4170-a723-f48c2bae5e0f
  ws-opts:
    headers:
      Host: yelan.thelastronin.cloudns.org
    path: /linkws/afrhms16v.bestxray.buzz
- name: 美国-18
  network: ws
  port: 80
  server: 151.101.3.10
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: cefffd1d-cc58-4560-b4d1-44f1af528f30
  ws-opts:
    headers:
      Host: uni.fi
    path: /?ed=2048
- name: 美国-19
  network: ws
  port: 80
  server: 103.133.1.0
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 9dde0cfb-2f92-432e-9c52-6d2dec6803bb
  ws-opts:
    headers:
      Host: KnOtNrmV2rayOtanOtrmNnOtenOtl.tErmiUs-kAne-nOne.SARBAZIT.COM
    path: /
- name: 美国-20
  network: ws
  port: 80
  server: 151.101.64.155
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: 01cdddb2-384b-4eb6-8a62-e29572925698
  ws-opts:
    headers:
      Host: speedfaa.ir
    path: /speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa-speedfaa?ed=2048
- client-fingerprint: chrome
  name: 美国-21
  network: ws
  port: 443
  server: hajlab.ucdavis.edu
  servername: hajlab.ucdavis.edu
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: 6407d901-f9d0-4e14-b805-39cd7440bf63
  ws-opts:
    headers:
      Host: Join_Evay_vpn.ir
    path: /@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn----@Evay_vpn?ed=2560
- name: 美国-22
  network: ws
  port: 80
  server: 151.101.2.216
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: e8a196c0-b131-411f-99b9-6e48ec21e552
  ws-opts:
    headers:
      Host: bas-kon-iranii.ir
    path: /@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config?ed=2048
- name: 美国-23
  network: ws
  port: 80
  server: speedtest.net
  skip-cert-verify: false
  type: vless
  udp: true
  uuid: e8a196c0-b131-411f-99b9-6e48ec21e552
  ws-opts:
    headers:
      Host: bas-kon-iranii.ir
    path: /@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config/@Alfred_Config?ed=2048
- name: 美国-24
  network: ws
  password: bpb-trojan
  port: 443
  server: 172.64.150.145
  skip-cert-verify: true
  sni: mindrOOm-5cz.pAgEs.dEV
  type: trojan
  ws-opts:
    headers:
      Host: mindrOOm-5cz.pAgEs.dEV
    path: /trC8BM8bTsAF0AnLYL
- name: 越南-1
  password: 94d219c9-1afc-4d42-b090-8b3794764380
  port: 443
  server: std1.loadingip.com
  skip-cert-verify: true
  type: trojan
  udp: false
- name: 越南-2
  password: 94d219c9-1afc-4d42-b090-8b3794764380
  port: 443
  server: 36.50.134.26
  skip-cert-verify: true
  type: trojan
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 38个'
  - '手动选择: 38个'
  - '加拿大分区: 1个'
  - '中国分区: 4个'
  - '西班牙分区: 1个'
  - '美国分区: 24个'
  - '香港分区: 1个'
  - '爱尔兰分区: 1个'
  - '伊朗分区: 1个'
  - '俄罗斯联邦分区: 3个'
  - '越南分区: 2个'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 38个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: '手动选择: 38个'
  type: select
- filter: (?i)加拿大|CA|ca
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ca.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '加拿大分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 4个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)西班牙|ES|es
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/es.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '西班牙分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 24个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)爱尔兰|IE|ie
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ie.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '爱尔兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)伊朗|IR|ir
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ir.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '伊朗分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)俄罗斯联邦|RU|ru
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '俄罗斯联邦分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)越南|VN|vn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '越南分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
