allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 64
  cipher: auto
  name: 中国-1
  port: 35601
  server: 120.232.153.41
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: 德国-1
  password: telegram-id-privatevpns
  port: 22222
  server: 35.156.127.66
  skip-cert-verify: true
  sni: trojan.burgerip.co.uk
  type: trojan
- client-fingerprint: chrome
  name: 香港-1
  network: ws
  port: 23555
  server: 219.77.65.212
  servername: juzi8186.5112233.xyz
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: f775978b-6e22-41a8-ae5e-5f9779e6745f
  ws-opts:
    headers:
      Host: juzi8186.5112233.xyz
    path: /?ed=2560fp=randomfp=chrome
- name: 日本-1
  password: 8e4248f7-aae5-3a38-b99d-88bf1cd37e0d
  port: 443
  server: 35.75.8.137
  skip-cert-verify: true
  sni: fastly.cdn.steampipe.steamcontent.com
  type: trojan
  udp: true
- client-fingerprint: chrome
  name: 荷兰-1
  network: ws
  port: 1001
  server: 45.94.31.75
  servername: vless.ifx.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: vless.ifx.us.kg
    path: /?ed=2560fp=chrome
- client-fingerprint: chrome
  name: 新加坡-1
  network: ws
  port: 587
  server: 103.180.161.69
  servername: vless.ifx.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: vless.ifx.us.kg
    path: /?ed=2560
- client-fingerprint: chrome
  name: 美国-1
  network: ws
  port: 80
  server: 167.82.30.71
  servername: samane.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: samane.ir
    path: /4u7lAS4nPLtz0xPz?ed=2560
- client-fingerprint: ios
  name: 美国-2
  network: ws
  port: 80
  server: 167.82.30.71
  servername: samane.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: samane.ir
    path: /4u7lAS4nPLtz0xPz?ed=2560
- client-fingerprint: chrome
  name: 美国-3
  network: ws
  port: 443
  server: 199.232.5.79
  servername: mefa.ir
  skip-cert-verify: true
  tls: true
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: mefa.ir
    path: /H?ed=2560
- client-fingerprint: chrome
  name: 美国-4
  network: ws
  port: 587
  server: 206.223.84.99
  servername: vless.ifx.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: vless.ifx.us.kg
    path: /?ed=2560fp=chrome
- alterId: 0
  cipher: auto
  name: 美国-5
  network: ws
  port: 2082
  server: russia.com
  servername: ip26.6929198.xyz
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 5f3f09ad-89cb-4e94-a7ad-aa8239913555
  ws-opts:
    headers:
      Host: ip26.6929198.xyz
    path: /github.com/Alvin9999
- cipher: aes-128-gcm
  name: 美国-6
  password: shadowsocks
  port: 443
  server: 156.146.38.168
  type: ss
- client-fingerprint: chrome
  name: 美国-7
  network: ws
  port: 80
  server: 199.232.37.15
  servername: sara193.ir
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560
- client-fingerprint: chrome
  name: 美国-8
  network: ws
  port: 80
  server: 104.17.147.22
  servername: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 7d2dfb7a-2ecc-4448-bcbe-245a2092fe85
  ws-opts:
    headers:
      Host: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
    path: /Telegram-Xv2ry2?ed=512
- client-fingerprint: chrome
  name: 美国-9
  network: ws
  port: 80
  server: 167.82.30.71
  servername: samane.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: samane.ir
    path: /4u7lAS4nPLtz0xPz?ed=2560fp=chrome
- client-fingerprint: chrome
  name: 美国-10
  network: ws
  port: 587
  server: 45.33.123.73
  servername: vless.ifx.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: vless.ifx.us.kg
    path: /?ed=2560
- client-fingerprint: chrome
  name: 美国-11
  network: ws
  port: 80
  server: 167.82.30.71
  servername: samane.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: samane.ir
    path: /4u7lAS4nPLtz0xPz?ed=2560fp=chromefp=chrome
- client-fingerprint: chromefp=chrome
  name: 美国-12
  network: ws
  port: 80
  server: 167.82.30.71
  servername: samane.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: samane.ir
    path: /4u7lAS4nPLtz0xPz?ed=2560fp=chromefp=chrome
- client-fingerprint: chrome
  name: 美国-13
  network: ws
  port: 80
  server: www.speedtest.net
  servername: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 7d2dfb7a-2ecc-4448-bcbe-245a2092fe85
  ws-opts:
    headers:
      Host: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
    path: /Telegram-Xv2ry2?ed=512fp=chrome
- client-fingerprint: chrome
  name: 美国-14
  network: ws
  port: 80
  server: 162.159.129.60
  servername: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 7d2dfb7a-2ecc-4448-bcbe-245a2092fe85
  ws-opts:
    headers:
      Host: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
    path: /Telegram-Xv2ry2?ed=512fp=chromefp=chrome
- client-fingerprint: chrome
  name: 美国-15
  network: ws
  port: 80
  server: 199.232.37.15
  servername: sara193.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560fp=chrome
- client-fingerprint: chromefp=chrome
  name: 美国-16
  network: ws
  port: 80
  server: 162.159.129.60
  servername: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 7d2dfb7a-2ecc-4448-bcbe-245a2092fe85
  ws-opts:
    headers:
      Host: www.speedtest.net.nl1.72.18.432.20.20.20.20.ir.xn--g28h.dns-dynamic.net.
    path: /Telegram-Xv2ry2?ed=512fp=chromefp=chrome
- client-fingerprint: chromefp=chrome
  name: 美国-17
  network: ws
  port: 80
  server: 199.232.37.15
  servername: sara193.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: sara193.ir
    path: /BCXzvAcvSB7JzMWj?ed=2560fp=chromefp=chrome
- client-fingerprint: chrome
  name: 美国-18
  network: ws
  port: 587
  server: 165.154.163.236
  servername: vless.ifx.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: vless.ifx.us.kg
    path: /?ed=2560
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 24个'
  - '自动选择(国外): 22个'
  - '手动选择: 24个'
  - '中国分区: 1个'
  - '德国分区: 1个'
  - '香港分区: 1个'
  - '日本分区: 1个'
  - '荷兰分区: 1个'
  - '新加坡分区: 1个'
  - '美国分区: 18个'
  type: select
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all: true
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 24个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: false
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 22个'
  proxies:
  - 德国-1
  - 日本-1
  - 荷兰-1
  - 新加坡-1
  - 美国-1
  - 美国-2
  - 美国-3
  - 美国-4
  - 美国-5
  - 美国-6
  - 美国-7
  - 美国-8
  - 美国-9
  - 美国-10
  - 美国-11
  - 美国-12
  - 美国-13
  - 美国-14
  - 美国-15
  - 美国-16
  - 美国-17
  - 美国-18
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all: true
  name: '手动选择: 24个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)日本|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '日本分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)新加坡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '新加坡分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: true
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 18个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
