allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- name: 瑞士-1
  network: ws
  port: 80
  server: 185.18.250.12
  servername: ana-SErVICe.xAbjCDZ.wORkErs.deV
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  ws-opts:
    headers:
      Host: ana-SErVICe.xAbjCDZ.wORkErs.deV
    path: /1Y6MN5DFV8zB82Ai?ed=2560
- alterId: 0
  cipher: auto
  name: 中国-1
  port: 62506
  server: fiwejniavzoj.xn--fiqs8sjz2bull.com
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: ea695d03-e64c-4be0-a8ea-6346e286ef60
- alterId: 64
  cipher: auto
  name: 中国-2
  port: 44614
  server: 120.198.71.219
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 中国-3
  port: 45402
  server: 183.236.48.158
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: 中国-4
  password: QwwHvrnN
  port: 34185
  server: 36.151.192.201
  skip-cert-verify: true
  type: trojan
- alterId: 64
  cipher: auto
  name: 中国-5
  port: 48109
  server: 183.236.51.23
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alpn:
  - http/1.1
  client-fingerprint: chrome
  name: 德国-1
  network: ws
  port: 443
  server: 45.63.117.50
  servername: cpanel3.sassanidempire.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: fcf99985-147b-4c71-c3f2-f448e5a379f1
  ws-opts:
    headers:
      Host: cpanel3.sassanidempire.com
    path: /ws
- name: 法国-1
  password: 984e400bf5d541b7b0815913fe0c432a
  port: 443
  server: yournextcareerstep.online
  skip-cert-verify: true
  type: trojan
  udp: true
- name: 法国-2
  password: e8105dfd24414268b6c7652c63731097
  port: 443
  server: yournextcareerstep.online
  skip-cert-verify: true
  type: trojan
  udp: true
- name: 香港-1
  port: 4000
  server: ftq.ink
  tls: true
  type: http
- name: 香港-2
  port: 4000
  server: hk9.ftq.ink
  tls: true
  type: http
- client-fingerprint: chrome
  name: 日本-1
  network: ws
  port: 443
  server: 4.189.216.218
  servername: high.work.lzg.me
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 4c5f4cf8-b30a-4658-84bb-f0145dd123d4
  ws-opts:
    headers:
      Host: high.work.lzg.me
    path: /4c5f4cf8-b30a-4658-84bb-f0145dd123d4
- name: 摩尔多瓦-1
  network: tcp
  port: 443
  server: 185.235.243.133
  servername: tr-s.xor-vpn.ru
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 64a1796c-95f8-40e4-9a56-825823212648
- name: 美国-1
  password: 71409d3e488548e8bb076d229778f008
  port: 443
  server: jobsfortheworldtoday.com
  skip-cert-verify: true
  type: trojan
  udp: true
- name: 美国-2
  network: ws
  port: 8880
  server: 216.24.57.130
  servername: mohsenfitshr.wibibin259.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 1b6ae0f5-01dc-4b96-bca9-31c672dcf0aa
  ws-opts:
    headers:
      Host: mohsenfitshr.wibibin259.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1?ed=2560
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 15个'
  - '自动选择(国内): 7个'
  - '自动选择(国外): 8个'
  - '手动选择: 15个'
  - '瑞士分区: 1个'
  - '中国分区: 5个'
  - '德国分区: 1个'
  - '法国分区: 2个'
  - '香港分区: 2个'
  - '日本分区: 1个'
  - '摩尔多瓦分区: 1个'
  - '美国分区: 2个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 15个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 7个'
  proxies:
  - 中国-1
  - 中国-2
  - 中国-3
  - 中国-4
  - 中国-5
  - 香港-1
  - 香港-2
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 8个'
  proxies:
  - 瑞士-1
  - 德国-1
  - 法国-1
  - 法国-2
  - 日本-1
  - 摩尔多瓦-1
  - 美国-1
  - 美国-2
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 15个'
  type: select
- filter: (?i)瑞士|CH|ch
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ch.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '瑞士分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 5个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)法国|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '法国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)日本|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '日本分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)摩尔多瓦|MD|md
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/md.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '摩尔多瓦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
