allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: chacha20-ietf-poly1305
  name: 未知-1
  password: 09833a6f-4d46-426e-87fe-7793a5489f84
  port: 54030
  server: s-g04.loveroise.com
  type: ss
- alterId: 64
  cipher: auto
  name: 中国-1
  port: 54882
  server: 183.236.48.163
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- cipher: chacha20-ietf-poly1305
  name: 未知-2
  password: 09833a6f-4d46-426e-87fe-7793a5489f84
  port: 54102
  server: j-p04.loveroise.com
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 未知-3
  password: 09833a6f-4d46-426e-87fe-7793a5489f84
  port: 54012
  server: k-r03.loveroise.com
  type: ss
- alterId: 64
  cipher: auto
  name: 中国-2
  port: 41020
  server: 183.236.51.23
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- cipher: chacha20-ietf-poly1305
  name: 未知-4
  password: 09833a6f-4d46-426e-87fe-7793a5489f84
  port: 54002
  server: h-k02.loveroise.com
  type: ss
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 美国-1
  network: tcp
  port: 443
  server: us-w-s3.riot-cdn.com
  servername: contents.riot-cdn.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 61eb66a8-bc41-491e-a8dc-270874140f41
- alterId: 0
  cipher: auto
  name: 法国-1
  port: 80
  server: 147.45.68.132
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 28265dd5-342c-4d63-bdbb-a3259e2cf4d7
- client-fingerprint: random
  flow: xtls-rprx-vision
  name: 法国-2
  network: tcp
  port: 443
  reality-opts:
    public-key: 1gKloUYtea1EJfBcatiTkmJVdCbb6SfVrnL6Lz-RYj0
    short-id: '42'
  server: 51.158.243.62
  servername: cloudflare.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: fd17fd03-844b-4c4b-9551-27f2b055d4f8
- client-fingerprint: chrome
  name: 香港-1
  network: tcp
  port: 443
  reality-opts:
    public-key: DNdTBHyztOVJOBJQX91YXEhNkWbSAntqUoTFBHc6Clw
    short-id: 6ba85179e30d4fc2
  server: 8.217.246.186
  servername: b.travel-assets.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: e927b27f-e73c-4580-802e-9265fd7c40e8
- client-fingerprint: chrome
  name: 香港-2
  network: tcp
  port: 443
  reality-opts:
    public-key: DNdTBHyztOVJOBJQX91YXEhNkWbSAntqUoTFBHc6Clw
    short-id: 6ba85179e30d4fc2
  server: 47.76.136.169
  servername: www.dayuse.com.hk
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: e927b27f-e73c-4580-802e-9265fd7c40e8
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 以色列-1
  network: tcp
  port: 443
  reality-opts:
    public-key: -ALxkpd7Wi7WKs1dXND7yqoYQfJW8d4BctjfXIy0L1M
    short-id: b5ed878b
  server: 195.211.24.243
  servername: apple.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 71b60539-19bf-4282-b09f-7596ffc3cc8b
- cipher: chacha20-ietf-poly1305
  name: 日本-1
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)a7bbfde:185966
    mode: tls
    tls: false
  port: 2377
  server: 18.176.215.63
  type: ss
- name: 摩尔多瓦-1
  network: tcp
  port: 443
  server: 185.235.243.133
  servername: tr-s.xor-vpn.ru
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 64a1796c-95f8-40e4-9a56-825823212648
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 俄罗斯联邦-1
  network: tcp
  port: 443
  reality-opts:
    public-key: NsRSWMDMKxVFiry3uRJB8tG5rG8LdIJqTJvHK0Uc6Gw
    short-id: EeEFB5bF
  server: 185.40.153.191
  servername: vk.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 71b60539-19bf-4282-b09f-7596ffc3cc8b
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-2
  network: ws
  port: 6814
  server: 194.87.69.244
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 8765b365-4d13-4b15-b5cb-74a8a18b2260
  ws-opts:
    path: /
- alpn:
  - h3
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: 新加坡-1
  network: tcp
  port: 443
  server: 165.22.50.149
  servername: zoom.us
  skip-cert-verify: true
  tls: true
  type: vless
  uuid: 57252ea4-602b-4210-9a6c-f1588ea07f04
- name: 新加坡-2
  network: tcp
  port: 443
  server: 8.222.158.140
  servername: 147135010103.sec19org.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 3b9bc773-05eb-4d5f-8c1f-57342c0c4f40
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 土耳其-1
  network: tcp
  port: 13509
  reality-opts:
    public-key: IiuIighvDsor2v-vb5s3IJbNiqwLw568auiqoXxc7FM
  server: 176.98.41.45
  servername: www.sega.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: dbc34aa9-3cb1-477a-c47d-998f8badf0e8
- client-fingerprint: ios
  name: 美国-2
  network: tcp
  port: 18443
  reality-opts:
    public-key: 8233FxCRw1a_aCJ8d1HwHBMD_fABUNNW7rsrFe3vK0s
    short-id: e6658462
  server: phx-plus-1ddns.faforex.eu.org
  servername: www.tesla.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 86206c88-b8e3-4cb3-8932-3ca6ea1b6033
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 美国-3
  network: tcp
  port: 443
  server: 209.141.53.75
  servername: contents.riot-cdn.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 61eb66a8-bc41-491e-a8dc-270874140f41
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 21个'
  - '自动选择(国内): 4个'
  - '自动选择(国外): 17个'
  - '手动选择: 21个'
  - '未知分区: 4个'
  - '中国分区: 2个'
  - '美国分区: 3个'
  - '法国分区: 2个'
  - '香港分区: 2个'
  - '以色列分区: 1个'
  - '日本分区: 1个'
  - '摩尔多瓦分区: 1个'
  - '俄罗斯联邦分区: 2个'
  - '新加坡分区: 2个'
  - '土耳其分区: 1个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 21个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 4个'
  proxies:
  - 中国-1
  - 中国-2
  - 香港-1
  - 香港-2
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 17个'
  proxies:
  - 未知-1
  - 未知-2
  - 未知-3
  - 未知-4
  - 美国-1
  - 法国-1
  - 法国-2
  - 以色列-1
  - 日本-1
  - 摩尔多瓦-1
  - 俄罗斯联邦-1
  - 俄罗斯联邦-2
  - 新加坡-1
  - 新加坡-2
  - 土耳其-1
  - 美国-2
  - 美国-3
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 21个'
  type: select
- filter: (?i)未知|cn|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '未知分区: 4个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)法国|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '法国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)以色列|IL|il
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/il.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '以色列分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)日本|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '日本分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)摩尔多瓦|MD|md
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/md.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '摩尔多瓦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)俄罗斯联邦|RU|ru
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '俄罗斯联邦分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)新加坡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '新加坡分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)土耳其|TR|tr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '土耳其分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
