allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 0
  cipher: auto
  http-opts:
    headers:
      Host:
      - moi.ir
    method: GET
    path:
    - /
  name: 加拿大-1
  network: http
  port: 8881
  server: 159.203.20.140
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: db5afae4-ac23-41a6-8378-f307a9a47436
- cipher: chacha20-ietf-poly1305
  name: 中国-1
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 11413
  server: hkg-03-zz.manatraffic.top
  type: ss
  udp: true
- cipher: rc4-md5
  name: 中国-2
  obfs: plain
  obfs-param: cd2b692902.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: 40202
  protocol: auth_aes128_md5
  protocol-param: 92902:pFWGOQ
  server: 1.link-hub.blog
  type: ssr
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-3
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 12822
  server: twn-02-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 香港-1
  password: 3FB23A19-9424-40C7-9139-3540228283FA
  port: 40000
  server: hk.fastsoonlink.com
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-4
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 11561
  server: sgp-01-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-5
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 11562
  server: sgp-02-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-6
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19019
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-7
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19014
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-8
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19088
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-9
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 11563
  server: sgp-03-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-10
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 14201
  server: jpn-01-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-11
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 14202
  server: jpn-02-zz.manatraffic.top
  type: ss
  udp: true
- cipher: rc4-md5
  name: 中国-12
  obfs: plain
  obfs-param: cd2b692902.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: 40200
  protocol: auth_aes128_md5
  protocol-param: 92902:pFWGOQ
  server: 1.link-hub.blog
  type: ssr
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-13
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19013
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-14
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19006
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-15
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19003
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: 毛里求斯-1
  password: 64ddb7e7-618b-4413-bd14-8b28372cc2a3
  port: 51201
  server: a1.1tsm-sab2qkybzqc4ujzufu5yqppaomvbqfmrjunx7dmbde1ktmr.cv
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-16
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 13501
  server: usa-01-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-17
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19015
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 新加坡-1
  password: 3FB23A19-9424-40C7-9139-3540228283FA
  port: 40005
  server: sgp.fastsoonlink.com
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-18
  password: 3FB23A19-9424-40C7-9139-3540228283FA
  port: 40005
  server: 103.216.253.197
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-19
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19027
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-20
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19009
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-21
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19002
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-22
  password: 8771d456-6779-4c33-a796-b6defc67bc75
  port: 11412
  server: hkg-02-zz.manatraffic.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-23
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 16603
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: rc4-md5
  name: 中国-24
  obfs: plain
  obfs-param: cd2b692902.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: 40254
  protocol: auth_aes128_md5
  protocol-param: 92902:pFWGOQ
  server: 3.link-hub.click
  type: ssr
  udp: true
- cipher: rc4-md5
  name: 中国-25
  obfs: plain
  obfs-param: cd2b692902.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: 40255
  protocol: auth_aes128_md5
  protocol-param: 92902:pFWGOQ
  server: 3.link-hub.click
  type: ssr
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-26
  password: f807f0b8-ead7-4d6a-badd-faec149d3101
  port: 57813
  server: mmt.shlta.microsoft.51douyintv.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-27
  password: 1834fc79-7f4b-4e2b-9048-17c7b809fc44
  port: 19008
  server: yy1.vyunyunnode.top
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-28
  password: f807f0b8-ead7-4d6a-badd-faec149d3101
  port: 54192
  server: mmt.hzyd.microsoft.51douyintv.top
  type: ss
  udp: true
- http-opts:
    headers:
      Host:
      - www.speedtest.net
    method: GET
    path:
    - /
  name: 德国-1
  network: http
  port: 4687
  server: 217.195.194.46
  servername: www.speedtest.net
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: f1c66385-dcb3-4e03-aa31-6adf6708b146
- name: 德国-2
  password: '3782591447421952000'
  port: 443
  server: patient-ghost.treefrog761.one
  skip-cert-verify: true
  sni: patient-ghost.treefrog761.one
  type: trojan
  udp: true
- http-opts:
    headers:
      Host:
      - www.speedtest.net
    method: GET
    path:
    - /
  name: 德国-3
  network: http
  port: 4687
  server: dev4-vip.digitalldns.com
  servername: www.speedtest.net
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: f1c66385-dcb3-4e03-aa31-6adf6708b146
- http-opts:
    headers:
      Host:
      - www.speedtest.net
    method: GET
    path:
    - /
  name: 芬兰-1
  network: http
  port: 6587
  server: flv4-vip.digitalldns.com
  servername: www.speedtest.net
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: f1c66385-dcb3-4e03-aa31-6adf6708b146
- client-fingerprint: chrome
  name: 芬兰-2
  port: 443
  reality-opts:
    public-key: jG1boY63MivlimbwqJZPX1RfcQTtoPSOjMJz2YEWOns
    short-id: f7caf4
  server: bermudavpn24.jahanmataleb.ir
  servername: www.refersion.com
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: bc2d4bfe-cc5d-4382-8b9e-bf5242d9a295
- name: 香港-2
  password: b2d0b65a-616c-433d-8e7b-08af61017fa8
  port: 43396
  server: 45.146.232.172
  skip-cert-verify: false
  sni: q08m.vgraxiw73s.hasyaf.cn
  type: trojan
  udp: true
- name: 美国-1
  network: ws
  port: 80
  server: 66.235.200.58
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1
- name: 美国-2
  network: ws
  port: 80
  server: 66.235.200.149
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /
- name: 美国-3
  network: ws
  port: 80
  server: 66.235.200.30
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1
- name: 美国-4
  network: ws
  port: 80
  server: 66.235.200.30
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /
- name: 美国-5
  network: ws
  port: 80
  server: 66.235.200.5
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1
- name: 美国-6
  network: ws
  port: 80
  server: 66.235.200.149
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1
- client-fingerprint: chrome
  name: 美国-7
  port: 2046
  reality-opts:
    public-key: P0t-7rDdRNOg0bHvo-S_VgNWzcmXb5cB7b6qA1vtfE4
    short-id: d4fdce164f84219c
  server: 40.83.200.62
  servername: www.apple.com
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: ba00fea2-9c5b-46aa-895d-2e189715c374
- name: 美国-8
  network: ws
  port: 80
  server: 66.235.200.191
  servername: pormang.webhost99.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  udp: true
  uuid: e497da22-d020-40fb-a1fa-bc294066a2d2
  ws-opts:
    headers:
      Host: pormang.webhost99.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1
- alterId: 64
  cipher: auto
  name: 美国-9
  network: ws
  port: 30003
  server: 38.11.69.35
  skip-cert-verify: true
  tls: true
  type: vmess
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: www.52140341.xyz
    path: /path/1738143533474
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 47个'
  - '自动选择(国内): 30个'
  - '自动选择(国外): 17个'
  - '手动选择: 47个'
  - '加拿大分区: 1个'
  - '中国分区: 28个'
  - '香港分区: 2个'
  - '毛里求斯分区: 1个'
  - '新加坡分区: 1个'
  - '德国分区: 3个'
  - '芬兰分区: 2个'
  - '美国分区: 9个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 47个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 30个'
  proxies:
  - 中国-1
  - 中国-2
  - 中国-3
  - 香港-1
  - 中国-4
  - 中国-5
  - 中国-6
  - 中国-7
  - 中国-8
  - 中国-9
  - 中国-10
  - 中国-11
  - 中国-12
  - 中国-13
  - 中国-14
  - 中国-15
  - 中国-16
  - 中国-17
  - 中国-18
  - 中国-19
  - 中国-20
  - 中国-21
  - 中国-22
  - 中国-23
  - 中国-24
  - 中国-25
  - 中国-26
  - 中国-27
  - 中国-28
  - 香港-2
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 17个'
  proxies:
  - 加拿大-1
  - 毛里求斯-1
  - 新加坡-1
  - 德国-1
  - 德国-2
  - 德国-3
  - 芬兰-1
  - 芬兰-2
  - 美国-1
  - 美国-2
  - 美国-3
  - 美国-4
  - 美国-5
  - 美国-6
  - 美国-7
  - 美国-8
  - 美国-9
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 47个'
  type: select
- filter: (?i)加拿大|CA|ca
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ca.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '加拿大分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 28个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)毛里求斯|MU|mu
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/mu.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '毛里求斯分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)新加坡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '新加坡分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)芬兰|FI|fi
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fi.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '芬兰分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 9个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- GEOSITE,category-ai-chat-!cn,默认代理
- GEOSITE,bing,DIRECT
- GEOSITE,microsoft@cn,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
