allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: aes-256-cfb
  name: 比利时-1
  password: f8f7aCzcPKbsF8p3
  port: 989
  server: 192.71.249.71
  type: ss
- alterId: 0
  cipher: auto
  name: 巴西-1
  port: 8080
  server: vm.v2ray.com.br
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 7bc1cddb-e8a0-4742-8a15-4221c481e01f
- cipher: chacha20-ietf-poly1305
  name: 瑞士-1
  password: fMcrsQuZhCNiHBmXT80AhQ3mPK5alh/iLuDz4pILlYU=
  port: 44915
  server: 138.124.60.136
  type: ss
- name: 中国-1
  password: QwwHvrnN
  port: 36442
  server: 223.113.54.145
  skip-cert-verify: true
  type: trojan
- http-opts:
    headers:
      Host:
      - Telewebion.com
    method: GET
    path:
    - /
  name: 德国-1
  network: http
  port: 19984
  server: 188.245.215.46
  servername: Telewebion.com
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 13e15bfe-73f7-4bfe-a386-136451137fc3
- alterId: 0
  cipher: auto
  name: 德国-2
  port: 44484
  server: 78.47.102.195
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 8a2ce574-2b74-4f10-a28e-b6d852e3f725
- cipher: aes-128-gcm
  name: 英国-1
  password: shadowsocks
  port: 443
  server: 212.102.53.197
  type: ss
- cipher: aes-128-gcm
  name: 英国-2
  password: shadowsocks
  port: 443
  server: uk-dc1.yangon.club
  type: ss
- cipher: aes-256-cfb
  name: 危地马拉-1
  obfs: plain
  obfs-param: ''
  password: f8f7aCzcPKbsF8p3
  port: 989
  protocol: origin
  protocol-param: ''
  server: 170.80.111.5
  type: ssr
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: 美国-1
  network: ws
  port: 443
  server: zmaoz.faculty.ucdavis.edu
  servername: zmaoz.faculty.ucdavis.edu.
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: bfb490c9-18d0-48a4-cb72-e4cc9002afde
  ws-opts:
    headers:
      Host: fonmelo.com
    path: /olem/ws?ed=4096
- client-fingerprint: randomized
  name: 美国-2
  network: ws
  port: 443
  server: zmaoz.faculty.ucdavis.edu
  servername: zmaoz.faculty.ucdavis.edu
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 5ca4947a-3a0e-458e-9701-11e6805dae8f
  ws-opts:
    headers:
      Host: JOIN.unlimiteddev.4.4.4.4.wWw.CloudFlare.cOm.wWw.SpeedTeSt.cOm.Home.iRan.0.0.0.0.Hide.my.IP.xXx.333.22.1.CDN.Free.unlimiteddev.DDNS1-IP.nEt
    path: /@UnlimitedDev----@UnlimitedDev-----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev?ed=2480
- name: 哈萨克斯坦-1
  network: ws
  password: tg-fq521free
  port: 443
  server: 194.76.18.129
  skip-cert-verify: true
  sni: torjan.xn--xhq44j.eu.org
  type: trojan
  ws-opts:
    headers:
      Host: torjan.xn--xhq44j.eu.org
    path: /
- cipher: chacha20-ietf-poly1305
  name: 立陶宛-1
  password: cvII85TrW6n0OGyfpHVS1u
  port: 8080
  server: 45.87.175.181
  type: ss
- cipher: aes-128-gcm
  name: 荷兰-1
  password: shadowsocks
  port: 443
  server: 149.34.244.82
  type: ss
- cipher: aes-128-gcm
  name: 荷兰-2
  password: shadowsocks
  port: 443
  server: 149.34.244.77
  type: ss
- cipher: aes-256-cfb
  name: 波兰-1
  password: UkXRsXvR6buDMG2Y
  port: 9001
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-2
  password: c3NtHJ5ujV2tGDfj
  port: 9084
  server: 217.30.10.18
  type: ss
- name: 俄罗斯联邦-1
  network: ws
  password: tg-fq521free
  port: 443
  server: 45.67.215.95
  skip-cert-verify: true
  sni: torjan.xn--xhq44j.eu.org
  type: trojan
  ws-opts:
    headers:
      Host: torjan.xn--xhq44j.eu.org
    path: /
- alpn:
  - h3
  - h2
  - http/1.1
  grpc-opts:
    grpc-mode: gun
    grpc-service-name: Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-Telegramjoin:@V2Ray_Rolly-
  name: 瑞典-1
  network: grpc
  port: 2053
  server: 185.146.173.185
  servername: Ehhdheh.vshsbsbb-jzjsjb-vdhsh-mahdi-irancel.ir
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 97be46fc-0356-4594-858b-d36fc90bf413
- cipher: chacha20-ietf-poly1305
  name: 德国-3
  password: O4D8WTvkvIALxm+8sIH2rgpXizdNVcqjbcN0O1Rl9KQ=
  port: 10851
  server: 109.120.138.94
  type: ss
- cipher: aes-256-cfb
  name: 斯洛伐克-1
  password: f8f7aCzcPKbsF8p3
  port: 989
  server: 196.245.151.50
  type: ss
- name: 美国-3
  network: ws
  port: 8080
  server: xn--b6gac.eu.org
  servername: wwwvisacomsg.mshcgb8q.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 464d644c-9c10-4c02-9117-4c75b0c347cd
  ws-opts:
    headers:
      Host: wwwvisacomsg.mshcgb8q.workers.dev
    path: /ProxyIP=ProxyIP.US.fxxk.dedyn.io
- name: 美国-4
  network: ws
  port: 443
  server: 199.232.125.43
  servername: ELI-V2-RAY.COM
  skip-cert-verify: true
  tls: true
  type: vless
  uuid: ec1540bf-39b1-5901-bc00-4aa9c81e27af
  ws-opts:
    headers:
      Host: ELI-V2-RAY.COM
    path: /
- name: 美国-5
  network: ws
  password: tg-fq521free
  port: 443
  server: 216.24.57.30
  skip-cert-verify: true
  sni: torjan.xn--xhq44j.eu.org
  type: trojan
  ws-opts:
    headers:
      Host: torjan.xn--xhq44j.eu.org
    path: /
- cipher: chacha20-ietf-poly1305
  name: 美国-6
  password: 4p8Xip5R50r2guWgrffLUg
  port: 36325
  server: 3.147.48.100
  type: ss
- name: 美国-7
  network: ws
  password: tg-fq521free
  port: 443
  server: 198.62.62.67
  skip-cert-verify: true
  sni: torjan.xn--xhq44j.eu.org
  type: trojan
  ws-opts:
    headers:
      Host: torjan.xn--xhq44j.eu.org
    path: /
- name: 美国-8
  network: ws
  port: 80
  server: speedtest.net
  servername: JOIN.unlimiteddev.4.4.4.4.wWw.CloudFlare.cOm.wWw.SpeedTeSt.cOm.Home.iRan.0.0.0.0.Hide.my.IP.xXx.333.22.1.CDN.Free.unlimiteddev.DDNS1-IP.nEt
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 5ca4947a-3a0e-458e-9701-11e6805dae8f
  ws-opts:
    headers:
      Host: JOIN.unlimiteddev.4.4.4.4.wWw.CloudFlare.cOm.wWw.SpeedTeSt.cOm.Home.iRan.0.0.0.0.Hide.my.IP.xXx.333.22.1.CDN.Free.unlimiteddev.DDNS1-IP.nEt
    path: /@UnlimitedDev----@UnlimitedDev-----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev----@UnlimitedDev?ed=2480
- name: 美国-9
  password: Julius
  port: 443
  server: 104.219.41.229
  skip-cert-verify: true
  sni: miami.juliusnet.com
  type: trojan
- name: 美国-10
  network: ws
  port: 22222
  server: 98.85.198.21
  servername: telegram-channel-vlessconfig.sohala.uk
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 05519058-d2ac-4f28-9e4a-2b2a1386749e
  ws-opts:
    headers:
      Host: telegram-channel-vlessconfig.sohala.uk
    path: /telegram-channel-vlessconfig-ws
- alpn:
  - h2
  - http/1.1
  name: 美国-11
  network: tcp
  port: 443
  server: 147135001178.sec22org.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: e20ebe01-1815-4c09-8e77-fb2f168263ce
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: 美国-12
  network: ws
  port: 443
  server: 172.67.160.44
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: true
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 31个'
  - '自动选择(国内): 1个'
  - '自动选择(国外): 30个'
  - '手动选择: 31个'
  - '比利时分区: 1个'
  - '巴西分区: 1个'
  - '瑞士分区: 1个'
  - '中国分区: 1个'
  - '德国分区: 3个'
  - '英国分区: 2个'
  - '危地马拉分区: 1个'
  - '美国分区: 12个'
  - '哈萨克斯坦分区: 1个'
  - '立陶宛分区: 1个'
  - '荷兰分区: 2个'
  - '波兰分区: 2个'
  - '俄罗斯联邦分区: 1个'
  - '瑞典分区: 1个'
  - '斯洛伐克分区: 1个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 31个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 1个'
  proxies:
  - 中国-1
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 30个'
  proxies:
  - 比利时-1
  - 巴西-1
  - 瑞士-1
  - 德国-1
  - 德国-2
  - 英国-1
  - 英国-2
  - 危地马拉-1
  - 美国-1
  - 美国-2
  - 哈萨克斯坦-1
  - 立陶宛-1
  - 荷兰-1
  - 荷兰-2
  - 波兰-1
  - 波兰-2
  - 俄罗斯联邦-1
  - 瑞典-1
  - 德国-3
  - 斯洛伐克-1
  - 美国-3
  - 美国-4
  - 美国-5
  - 美国-6
  - 美国-7
  - 美国-8
  - 美国-9
  - 美国-10
  - 美国-11
  - 美国-12
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 31个'
  type: select
- filter: (?i)比利时|BE|be
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/be.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '比利时分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)巴西|BR|br
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/br.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '巴西分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)瑞士|CH|ch
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ch.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '瑞士分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)英国|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '英国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)危地马拉|GT|gt
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gt.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '危地马拉分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 12个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)哈萨克斯坦|KZ|kz
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kz.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '哈萨克斯坦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)立陶宛|LT|lt
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lt.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '立陶宛分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)波兰|PL|pl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '波兰分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)俄罗斯联邦|RU|ru
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '俄罗斯联邦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)瑞典|SE|se
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/se.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '瑞典分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)斯洛伐克|SK|sk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '斯洛伐克分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
