allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 64
  cipher: auto
  name: 中国-1
  port: 41020
  server: 183.236.51.23
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 0
  cipher: auto
  name: 中国-2
  network: ws
  port: 25284
  server: cu.awslcn.info
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 243eab52-9ac1-405c-887c-eb112c0985b8
  ws-opts:
    headers:
      Host: cu.awslcn.info
    path: /
- client-fingerprint: ios
  flow: xtls-rprx-vision
  name: 德国-1
  port: 443
  server: 132.145.237.172
  servername: jsdownloadde1.xn--4gq62f52gopi49k.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 95eb72fe-e967-4540-ac10-069c8a95c6d7
- cipher: rc4-md5
  name: 德国-2
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 193.108.119.230
  type: ss
- name: 德国-3
  network: ws
  port: 2083
  server: tuea.vact.ir
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: b427ed05-cc5f-4f88-ab96-f04a6e30300b
- client-fingerprint: random
  flow: xtls-rprx-vision
  name: 法国-1
  port: 443
  reality-opts:
    public-key: 1gKloUYtea1EJfBcatiTkmJVdCbb6SfVrnL6Lz-RYj0
    short-id: '42'
  server: 51.158.243.62
  servername: cloudflare.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: fd17fd03-844b-4c4b-9551-27f2b055d4f8
- cipher: rc4-md5
  name: 英国-1
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 169.150.210.233
  type: ss
- cipher: rc4-md5
  name: 英国-2
  obfs: plain
  obfs-param: ''
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  protocol: origin
  protocol-param: ''
  server: 169.150.210.233
  type: ssr
- name: 直布罗陀-1
  port: 2198
  server: 95.164.3.165
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- name: 香港-1
  port: 4000
  server: hk9.ftq.ink
  tls: true
  type: http
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 印度-1
  port: 443
  server: 144.24.97.225
  servername: jsdownloadin1.xn--4gq62f52gopi49k.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 95eb72fe-e967-4540-ac10-069c8a95c6d7
- http-opts:
    headers:
      Host:
      - telewebion.com
    method: GET
    path:
    - /
  name: 伊朗-1
  network: http
  port: 56185
  server: 89.42.196.36
  servername: telewebion.com
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: d0d09937-05a7-a662-dd40-d09b667e1c28
- cipher: aes-256-cfb
  name: 日本-1
  password: amazonskr05
  port: 443
  server: 54.178.84.59
  type: ss
- cipher: aes-256-cfb
  name: 韩国-1
  password: amazonskr05
  port: 443
  server: 52.79.73.137
  type: ss
- name: 未知-1
  password: '3723507166611775488'
  port: 443
  server: fluent-bat.treefrog761.one
  skip-cert-verify: false
  sni: fluent-bat.treefrog761.one
  type: trojan
- name: 韩国-2
  password: '3723507166611775488'
  port: 443
  server: 13.124.1.64
  skip-cert-verify: true
  sni: fluent-bat.treefrog761.one
  type: trojan
- client-fingerprint: chrome
  flow: xtls-rprx-vision
  name: 韩国-3
  port: 443
  server: 193.122.110.86
  servername: jsdownloadkr.xn--4gq62f52gopi49k.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 95eb72fe-e967-4540-ac10-069c8a95c6d7
- cipher: aes-256-cfb
  name: 韩国-4
  password: amazonskr05
  port: 443
  server: 43.203.127.152
  type: ss
- cipher: aes-128-gcm
  name: 荷兰-1
  password: shadowsocks
  port: 443
  server: 149.34.244.82
  type: ss
- cipher: aes-128-gcm
  name: 荷兰-2
  password: shadowsocks
  port: 443
  server: 149.34.244.68
  type: ss
- http-opts:
    headers:
      Host:
      - Speedtest.net
    method: GET
    path:
    - /
  name: 荷兰-3
  network: http
  port: 23701
  server: 146.190.16.108
  servername: Speedtest.net
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 677a41e5-dbe6-429b-8f91-cc014b1ae1bd
- name: 荷兰-4
  port: 2198
  server: 103.106.2.243
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- name: 荷兰-5
  port: 2198
  server: 188.119.112.3
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- name: 荷兰-6
  port: 2198
  server: 80.92.206.33
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- name: 荷兰-7
  port: 2198
  server: 95.164.87.21
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- http-opts:
    headers:
      Host:
      - neshan.org
    method: GET
    path:
    - /
  name: 荷兰-8
  network: http
  port: 443
  server: srv1-d.gamekade.tech
  servername: neshan.org
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: f97c0600-b5c9-465d-9c14-34cfb8a6e9dc
- name: 荷兰-9
  port: 2198
  server: 185.236.233.55
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- name: 荷兰-10
  port: 2198
  server: 94.131.106.53
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- cipher: chacha20-ietf-poly1305
  name: 俄罗斯联邦-1
  password: TLzTbRU2xuSDMOU9o8e0QQ
  port: 3832
  server: 77.73.70.200
  type: ss
- client-fingerprint: safari
  name: 美国-1
  port: 18443
  reality-opts:
    public-key: 8233FxCRw1a_aCJ8d1HwHBMD_fABUNNW7rsrFe3vK0s
    short-id: e6658462
  server: phx-plus-1ddns.faforex.eu.org
  servername: www.tesla.com
  skip-cert-verify: false
  tls: true
  type: vless
  udp: true
  uuid: 311faab5-5e89-4f41-b2a4-ca4452508cc6
- client-fingerprint: ios
  name: 美国-2
  port: 18443
  reality-opts:
    public-key: 8233FxCRw1a_aCJ8d1HwHBMD_fABUNNW7rsrFe3vK0s
    short-id: e6658462
  server: phx-plus-1ddns.faforex.eu.org
  servername: www.tesla.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 86206c88-b8e3-4cb3-8932-3ca6ea1b6033
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 31个'
  - '自动选择(国内): 3个'
  - '自动选择(国外): 28个'
  - '手动选择: 31个'
  - '中国分区: 2个'
  - '德国分区: 3个'
  - '法国分区: 1个'
  - '英国分区: 2个'
  - '直布罗陀分区: 1个'
  - '香港分区: 1个'
  - '印度分区: 1个'
  - '伊朗分区: 1个'
  - '日本分区: 1个'
  - '韩国分区: 4个'
  - '未知分区: 1个'
  - '荷兰分区: 10个'
  - '俄罗斯联邦分区: 1个'
  - '美国分区: 2个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 31个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 3个'
  proxies:
  - 中国-1
  - 中国-2
  - 香港-1
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 28个'
  proxies:
  - 德国-1
  - 德国-2
  - 德国-3
  - 法国-1
  - 英国-1
  - 英国-2
  - 直布罗陀-1
  - 印度-1
  - 伊朗-1
  - 日本-1
  - 韩国-1
  - 未知-1
  - 韩国-2
  - 韩国-3
  - 韩国-4
  - 荷兰-1
  - 荷兰-2
  - 荷兰-3
  - 荷兰-4
  - 荷兰-5
  - 荷兰-6
  - 荷兰-7
  - 荷兰-8
  - 荷兰-9
  - 荷兰-10
  - 俄罗斯联邦-1
  - 美国-1
  - 美国-2
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 31个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)法国|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '法国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)英国|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '英国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)直布罗陀|GI|gi
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gi.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '直布罗陀分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)印度|IN|in
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/in.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '印度分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)伊朗|IR|ir
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ir.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '伊朗分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)日本|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '日本分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)韩国|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '韩国分区: 4个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)未知|cn|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '未知分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 10个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)俄罗斯联邦|RU|ru
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '俄罗斯联邦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
