allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- client-fingerprint: random
  name: 哥斯达黎加-1
  network: ws
  port: 443
  server: 190.93.246.128
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- http-opts:
    headers:
      Host:
      - Telewebion.com
    method: GET
    path:
    - /
  name: 德国-1
  network: http
  port: 19984
  server: 188.245.215.46
  servername: Telewebion.com
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 13e15bfe-73f7-4bfe-a386-136451137fc3
- alterId: 0
  cipher: auto
  name: 德国-2
  port: 4035
  server: 138.201.44.49
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 9398b3da-690f-4648-abb7-9c4118449159
- name: 德国-3
  network: ws
  port: 443
  server: 212.224.93.93
  servername: blog.codegethub.org
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 14ba4514-3846-45c0-aec6-444e5451b95c
  ws-opts:
    headers:
      Host: blog.codegethub.org
    path: /ws@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel
- cipher: rc4-md5
  name: 法国-1
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 51.158.244.38
  type: ss
- cipher: aes-128-gcm
  name: 英国-1
  password: shadowsocks
  port: 443
  server: 212.102.53.193
  type: ss
- name: 香港-1
  network: ws
  port: 443
  server: 8.218.148.106
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 香港-2
  port: 4000
  server: ftq.ink
  tls: true
  type: http
- cipher: chacha20-ietf-poly1305
  name: 印度-1
  password: 2S39h4RMyPdGcfcltg1rwD
  port: 55305
  server: 64.227.183.64
  type: ss
- cipher: aes-128-gcm
  name: 荷兰-1
  password: shadowsocks
  port: 443
  server: 149.34.244.82
  type: ss
- name: 新加坡-1
  network: ws
  port: 443
  server: 8.222.132.145
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 新加坡-2
  network: ws
  port: 443
  server: 47.245.120.119
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 新加坡-3
  network: ws
  port: 443
  server: 8.222.135.109
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 新加坡-4
  network: ws
  port: 443
  server: 8.219.55.76
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 新加坡-5
  network: ws
  port: 443
  server: 8.219.79.144
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 新加坡-6
  network: ws
  port: 443
  server: 8.219.129.213
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 新加坡-7
  network: ws
  port: 443
  server: 8.222.239.199
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 新加坡-8
  network: ws
  port: 443
  server: 47.245.87.17
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 新加坡-9
  network: ws
  port: 443
  server: 8.222.247.175
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 新加坡-10
  network: ws
  port: 443
  server: 8.222.222.203
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 新加坡-11
  network: ws
  port: 443
  server: 47.245.126.194
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 美国-1
  network: ws
  port: 443
  server: 104.24.139.27
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- cipher: aes-128-cfb
  name: 美国-2
  password: shadowsocks
  port: 443
  server: 184.170.241.194
  type: ss
- cipher: aes-128-cfb
  name: 美国-3
  obfs: plain
  obfs-param: ''
  password: shadowsocks
  port: 443
  protocol: origin
  protocol-param: ''
  server: 184.170.241.194
  type: ssr
- client-fingerprint: random
  name: 美国-4
  network: ws
  port: 443
  server: 172.64.160.120
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- cipher: rc4-md5
  name: 美国-5
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 79.110.53.169
  type: ss
  udp: true
- cipher: aes-256-gcm
  name: 美国-6
  password: pKEW8JPByTVTLtM
  port: 443
  server: 38.75.136.21
  type: ss
- client-fingerprint: random
  name: 美国-7
  network: ws
  port: 443
  server: 104.24.186.216
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- client-fingerprint: random
  name: 美国-8
  network: ws
  port: 443
  server: 104.24.136.104
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- client-fingerprint: random
  name: 美国-9
  network: ws
  port: 443
  server: 104.24.49.64
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- client-fingerprint: random
  name: 美国-10
  network: ws
  port: 443
  server: 188.114.97.158
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 美国-11
  network: ws
  port: 8443
  server: 104.18.38.147
  servername: server39.998877.best
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 11338fbe-71f7-47da-bc29-e74780eda3d3
  ws-opts:
    headers:
      Host: server39.998877.best
    path: /drtgoiuy/fd?ed=2560
- name: 美国-12
  network: ws
  port: 8443
  server: 172.64.149.109
  servername: server39.998877.best
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 11338fbe-71f7-47da-bc29-e74780eda3d3
  ws-opts:
    headers:
      Host: server39.998877.best
    path: /drtgoiuy/fd?ed=2560
- name: 美国-13
  network: ws
  port: 443
  server: 104.24.49.64
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /
- client-fingerprint: random
  name: 美国-14
  network: ws
  port: 443
  server: 104.16.59.58
  servername: lhxt.xiaomi.win
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 31f81de4-c0c3-4aa0-9b1d-dea8906a2ed1
  ws-opts:
    headers:
      Host: lhxt.xiaomi.win
    path: /?ed=2560
- name: 美国-15
  network: ws
  port: 443
  server: 199.232.125.43
  servername: ELI-V2-RAY.COM
  skip-cert-verify: true
  tls: true
  type: vless
  uuid: ec1540bf-39b1-5901-bc00-4aa9c81e27af
  ws-opts:
    headers:
      Host: ELI-V2-RAY.COM
    path: /
- cipher: aes-256-gcm
  name: 美国-16
  password: cdBIDV42DCwnfIN
  port: 8119
  server: 38.75.136.21
  type: ss
- cipher: aes-256-gcm
  name: 美国-17
  password: g5MeD6Ft3CWlJId
  port: 5004
  server: 38.75.136.21
  type: ss
- cipher: aes-256-gcm
  name: 美国-18
  password: e4FCWrgpkji3QY
  port: 9101
  server: 38.75.136.21
  type: ss
- name: 美国-19
  network: ws
  port: 80
  server: AT3.fast.hosting-ip.com
  servername: kazemi211zerofun.coM
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: ff45f39c-0055-48c5-962e-c2684e613e75
  ws-opts:
    headers:
      Host: kazemi211zerofun.coM
    path: /telegram-NUFiLTER,telegram-NUFiLTER,telegram-NUFiLTER,telegram-NUFiLTER,telegram-NUFiLTER,telegram-NUFiLTER,telegram-NUFiLTER,telegram-NUFiLTER?ed=80
- name: 美国-20
  network: ws
  port: 8443
  server: us6.998998.best
  servername: server39.998877.best
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 11338fbe-71f7-47da-bc29-e74780eda3d3
  ws-opts:
    headers:
      Host: server39.998877.best
    path: /drtgoiuy/fd?ed=2560
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 41个'
  - '自动选择(国内): 2个'
  - '自动选择(国外): 39个'
  - '手动选择: 41个'
  - '哥斯达黎加分区: 1个'
  - '德国分区: 3个'
  - '法国分区: 1个'
  - '英国分区: 1个'
  - '香港分区: 2个'
  - '印度分区: 1个'
  - '荷兰分区: 1个'
  - '新加坡分区: 11个'
  - '美国分区: 20个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 41个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 2个'
  proxies:
  - 香港-1
  - 香港-2
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 39个'
  proxies:
  - 哥斯达黎加-1
  - 德国-1
  - 德国-2
  - 德国-3
  - 法国-1
  - 英国-1
  - 印度-1
  - 荷兰-1
  - 新加坡-1
  - 新加坡-2
  - 新加坡-3
  - 新加坡-4
  - 新加坡-5
  - 新加坡-6
  - 新加坡-7
  - 新加坡-8
  - 新加坡-9
  - 新加坡-10
  - 新加坡-11
  - 美国-1
  - 美国-2
  - 美国-3
  - 美国-4
  - 美国-5
  - 美国-6
  - 美国-7
  - 美国-8
  - 美国-9
  - 美国-10
  - 美国-11
  - 美国-12
  - 美国-13
  - 美国-14
  - 美国-15
  - 美国-16
  - 美国-17
  - 美国-18
  - 美国-19
  - 美国-20
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 41个'
  type: select
- filter: (?i)哥斯达黎加|CR|cr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '哥斯达黎加分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)法国|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '法国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)英国|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '英国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)印度|IN|in
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/in.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '印度分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)新加坡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '新加坡分区: 11个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 20个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
