allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 64
  cipher: auto
  name: 中国-1
  port: 45402
  server: 183.236.48.158
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 0
  cipher: auto
  name: 中国-2
  port: 60852
  server: fiwejniavzoj.xn--fiqs8sjz2bull.com
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 17e51677-587d-4312-972a-3f51afd2fe4f
- alterId: 64
  cipher: auto
  name: 中国-3
  port: 41020
  server: 183.236.51.23
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: 中国-4
  password: QwwHvrnN
  port: 42395
  server: 36.151.192.239
  skip-cert-verify: true
  type: trojan
- cipher: rc4-md5
  name: 中国-5
  obfs: plain
  obfs-param: cd5ed74592.6602b8463464108506.microsoft.com
  password: ENZ52K
  port: 40243
  protocol: auth_aes128_md5
  protocol-param: 74592:o4fbeopsgcf
  server: 28b09af269781f9b.cdn.jiashule.com
  type: ssr
  udp: true
- alterId: 64
  cipher: auto
  name: 中国-6
  port: 40434
  server: 183.236.51.23
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: 中国-7
  password: 38571ca6-6692-4559-b901-0bc5826b7661
  port: 60194
  server: ru0195.alibabaokz.com
  skip-cert-verify: true
  sni: ru0195.alibabaokz.com
  type: trojan
- alpn:
  - h2
  client-fingerprint: chrome
  name: 德国-1
  network: tcp
  port: 8443
  server: 89.187.169.71
  servername: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
  skip-cert-verify: true
  tls: true
  type: vless
  uuid: 6ff213b8-ccc7-4b5a-b4aa-37f7b792a1f1
- alterId: 0
  cipher: auto
  name: 德国-2
  network: ws
  port: 10004
  server: 45.154.207.99
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 0084b5d0-8966-4398-87f8-d5d8b64aa356
  ws-opts:
    headers:
      Host: 45.154.207.99
    path: /github.com/Alvin9999
- name: 德国-3
  network: ws
  port: 443
  server: 212.224.93.93
  servername: blog.codegethub.org
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 14ba4514-3846-45c0-aec6-444e5451b95c
  ws-opts:
    headers:
      Host: blog.codegethub.org
    path: /ws@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: 法国-1
  network: tcp
  port: 443
  server: en.linceedab.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 24f7f8e5-dbe5-4cde-e018-2b74a00b6d69
- alpn:
  - h2
  - http/1.1
  client-fingerprint: chrome
  name: 法国-2
  network: tcp
  port: 443
  server: 57.128.178.253
  servername: en.linceedab.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 24f7f8e5-dbe5-4cde-e018-2b74a00b6d69
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: 香港-1
  network: http
  port: 34728
  server: 149.104.15.104
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: c94a21b5-43f6-477d-82a6-cdae1de397c3
- name: 香港-2
  port: 4000
  server: ftq.ink
  tls: true
  type: http
- name: 香港-3
  port: 4000
  server: hk9.ftq.ink
  tls: true
  type: http
- alterId: 0
  cipher: auto
  name: 意大利-1
  network: ws
  port: 443
  server: 158.180.228.226
  servername: beyonddsz.cfd
  skip-cert-verify: false
  tls: true
  type: vmess
  uuid: 9b456c2a-f2c1-45e1-87a9-b7628b04bb24
  ws-opts:
    headers:
      Host: beyonddsz.cfd
    path: /linkws
- name: 摩尔多瓦-1
  network: tcp
  port: 443
  server: 185.235.243.133
  servername: tr-s.xor-vpn.ru
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 64a1796c-95f8-40e4-9a56-825823212648
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-1
  network: ws
  port: 29025
  server: 194.87.69.50
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: eaee29bf-f18c-455a-ac9b-43a500f7d2aa
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-2
  network: ws
  port: 29025
  server: 195.58.49.86
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: ce329057-27f0-407b-818a-cda5d1f84601
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-3
  network: ws
  port: 29025
  server: 195.58.49.86
  servername: 195.58.49.86
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 7f21512a-240a-477d-8e83-1fba50a3eda0
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-4
  network: ws
  port: 29025
  server: 195.58.49.50
  servername: 195.58.49.50
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: b0c478e9-972f-4af6-aadb-f4f6e457e35f
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-5
  network: ws
  port: 29025
  server: 195.58.49.42
  servername: 195.58.49.42
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: e561fdb8-737c-4423-a72c-7831b7d3739d
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-6
  network: ws
  port: 29025
  server: 194.87.69.52
  servername: 194.87.69.52
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: e561fdb8-737c-4423-a72c-7831b7d3739d
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-7
  network: ws
  port: 29025
  server: 195.58.49.42
  servername: 195.58.49.42
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 180999db-5a60-4cea-a289-544961ee7c62
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-8
  network: ws
  port: 29025
  server: 195.58.49.50
  servername: 195.58.49.50
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 7f21512a-240a-477d-8e83-1fba50a3eda0
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-9
  network: ws
  port: 29025
  server: 195.58.49.86
  servername: 195.58.49.86
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 180999db-5a60-4cea-a289-544961ee7c62
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-10
  network: ws
  port: 29025
  server: 195.58.49.50
  servername: 195.58.49.50
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 59c9c12d-7b09-46dc-ab42-21ad771fb696
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-11
  network: ws
  port: 29025
  server: 195.58.49.50
  servername: 195.58.49.50
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 727d1e03-2aed-4190-bff5-30890097c1c4
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-12
  network: ws
  port: 29025
  server: 194.87.69.52
  servername: 194.87.69.52
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 180999db-5a60-4cea-a289-544961ee7c62
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-13
  network: ws
  port: 29025
  server: 195.58.49.86
  servername: 195.58.49.86
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: b0c478e9-972f-4af6-aadb-f4f6e457e35f
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-14
  network: ws
  port: 29025
  server: 194.87.69.52
  servername: 194.87.69.52
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: b0c478e9-972f-4af6-aadb-f4f6e457e35f
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-15
  network: ws
  port: 29025
  server: 195.58.49.42
  servername: 195.58.49.42
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 59c9c12d-7b09-46dc-ab42-21ad771fb696
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-16
  network: ws
  port: 29025
  server: 195.58.49.86
  servername: 195.58.49.86
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 727d1e03-2aed-4190-bff5-30890097c1c4
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-17
  network: ws
  port: 29025
  server: 195.58.49.42
  servername: 195.58.49.42
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: b0c478e9-972f-4af6-aadb-f4f6e457e35f
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-18
  network: ws
  port: 29025
  server: 194.87.69.50
  servername: 194.87.69.50
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 59c9c12d-7b09-46dc-ab42-21ad771fb696
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-19
  network: ws
  port: 29025
  server: 194.87.69.52
  servername: 194.87.69.52
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 727d1e03-2aed-4190-bff5-30890097c1c4
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-20
  network: ws
  port: 29025
  server: 195.58.49.42
  servername: 195.58.49.42
  skip-cert-verify: true
  tls: false
  type: vmess
  udp: true
  uuid: 7f21512a-240a-477d-8e83-1fba50a3eda0
  ws-opts:
    path: /
- name: 乌克兰-1
  network: tcp
  port: 443
  server: 5.188.6.73
  servername: 005188006073.sec1org.com
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 7582e721-8c32-4fb1-8669-b3fae590f3eb
- name: 美国-1
  network: ws
  port: 8880
  server: 216.24.57.130
  servername: mohsenfitshr.wibibin259.workers.dev
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 1b6ae0f5-01dc-4b96-bca9-31c672dcf0aa
  ws-opts:
    headers:
      Host: mohsenfitshr.wibibin259.workers.dev
    path: /@AZARBAYJAB1@AZARBAYJAB1@AZARBAYJAB1?ed=2560
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 39个'
  - '自动选择(国内): 10个'
  - '自动选择(国外): 29个'
  - '手动选择: 39个'
  - '中国分区: 7个'
  - '德国分区: 3个'
  - '法国分区: 2个'
  - '香港分区: 3个'
  - '意大利分区: 1个'
  - '摩尔多瓦分区: 1个'
  - '俄罗斯联邦分区: 20个'
  - '乌克兰分区: 1个'
  - '美国分区: 1个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 39个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 10个'
  proxies:
  - 中国-1
  - 中国-2
  - 中国-3
  - 中国-4
  - 中国-5
  - 中国-6
  - 中国-7
  - 香港-1
  - 香港-2
  - 香港-3
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 29个'
  proxies:
  - 德国-1
  - 德国-2
  - 德国-3
  - 法国-1
  - 法国-2
  - 意大利-1
  - 摩尔多瓦-1
  - 俄罗斯联邦-1
  - 俄罗斯联邦-2
  - 俄罗斯联邦-3
  - 俄罗斯联邦-4
  - 俄罗斯联邦-5
  - 俄罗斯联邦-6
  - 俄罗斯联邦-7
  - 俄罗斯联邦-8
  - 俄罗斯联邦-9
  - 俄罗斯联邦-10
  - 俄罗斯联邦-11
  - 俄罗斯联邦-12
  - 俄罗斯联邦-13
  - 俄罗斯联邦-14
  - 俄罗斯联邦-15
  - 俄罗斯联邦-16
  - 俄罗斯联邦-17
  - 俄罗斯联邦-18
  - 俄罗斯联邦-19
  - 俄罗斯联邦-20
  - 乌克兰-1
  - 美国-1
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 39个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 7个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)法国|FR|fr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '法国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)意大利|IT|it
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/it.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '意大利分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)摩尔多瓦|MD|md
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/md.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '摩尔多瓦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)俄罗斯联邦|RU|ru
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '俄罗斯联邦分区: 20个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)乌克兰|UA|ua
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ua.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '乌克兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
