allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- alterId: 64
  cipher: auto
  name: 中国-1
  port: 41020
  server: 183.236.51.23
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- cipher: rc4-md5
  name: 英国-1
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 146.70.61.18
  type: ss
  udp: true
- name: 香港-1
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 40793
  server: 43.198.108.18
  skip-cert-verify: true
  sni: hk12.bilibili.com
  type: trojan
- name: 香港-2
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 48539
  server: 1906e95f0a4e34cca3d5618e3498505d.v1.cac.node-is.green
  skip-cert-verify: true
  sni: hk12.bilibili.com
  type: trojan
- name: 香港-3
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 49089
  server: eb0aa4fcce49b0399bc0f109cd6a0296.v1.cac.node-is.green
  skip-cert-verify: true
  sni: jp12.bilibili.com
  type: trojan
  udp: true
- name: 香港-4
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 49782
  server: 7c0bb8d8872425b41520a1a9ad77fa89.v1.cac.node-is.green
  skip-cert-verify: true
  sni: jp12.bilibili.com
  type: trojan
- name: 香港-5
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 49089
  server: 16.163.104.216
  skip-cert-verify: true
  sni: jp12.bilibili.com
  type: trojan
- name: 香港-6
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 40793
  server: 18.162.188.231
  skip-cert-verify: true
  sni: hk12.bilibili.com
  type: trojan
- name: 香港-7
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 44991
  server: 18.163.48.140
  skip-cert-verify: true
  sni: us1.bilibili.com
  type: trojan
- name: 香港-8
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 41790
  server: ddbfb45e8b47580a5b2c2b5e43fa9213.v1.cac.node-is.green
  skip-cert-verify: true
  sni: us1.bilibili.com
  type: trojan
- name: 香港-9
  password: aa6ddd2f-d1cf-4a52-ba1b-2640c41a7856
  port: 44991
  server: 0bce075b5465c22ad8c82382a5df74ad.v1.cac.node-is.green
  skip-cert-verify: true
  sni: us1.bilibili.com
  type: trojan
  udp: true
- name: 哈萨克斯坦-1
  network: ws
  port: 443
  server: 31.43.179.46
  servername: vbbc.ylks01.eu.org
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 6fd4f5b4-7460-4b78-9d25-c0c285b23ce4
  ws-opts:
    headers:
      Host: vbbc.ylks01.eu.org
    path: /?ed=2560
- cipher: chacha20-ietf-poly1305
  name: 拉脱维亚-1
  password: f8f7aCzcPKbsF8p3
  port: 990
  server: 46.183.217.232
  type: ss
  udp: true
- cipher: aes-128-gcm
  name: 荷兰-1
  password: shadowsocks
  port: 443
  server: 149.34.244.82
  type: ss
- cipher: aes-256-cfb
  name: 波兰-1
  password: UkXRsXvR6buDMG2Y
  port: 9001
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-2
  password: c3NtHJ5ujV2tGDfj
  port: 9084
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-3
  password: rpgbNnU9rDDU4aWZ
  port: 9094
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-4
  password: FG5ddLsMPbV5CutE
  port: 9050
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-5
  password: TN2YqghxeFDKZfLU
  port: 9037
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-6
  password: BejrQvtu9sqUeNuZ
  port: 9024
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-7
  password: BNmAXXxAHYpTRdzu
  port: 9020
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 波兰-8
  password: f8f7aCzcPKbsF8p3
  port: 990
  server: 92.118.205.228
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-9
  password: BwcAUZk8hUFAkDGN
  port: 9031
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-10
  password: FAdUvMJUq5vDgKEq
  port: 9006
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-11
  password: M3t2ZEQcMGRWBjRa
  port: 9011
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-12
  password: gYCYXfkUQEs2TaJQ
  port: 9038
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-13
  password: TPqX8edgbAURcAMb
  port: 9079
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-14
  password: EXN3S3eQpjE7EJu8
  port: 9027
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-15
  password: f63gg8EruDnUrmz4
  port: 9010
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-16
  password: U6qnYRhfyDmn8sgn
  port: 9041
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: rc4-md5
  name: 新加坡-1
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 68.183.235.122
  type: ss
  udp: true
- alterId: 0
  cipher: auto
  name: 新加坡-2
  port: 443
  server: suddaehihub.sudda.store
  skip-cert-verify: true
  tls: true
  type: vmess
  uuid: ad2cea64-7ce8-46eb-b898-5b3a0937416f
- cipher: aes-256-cfb
  name: 美国-1
  password: amazonskr05
  port: 443
  server: 54.202.63.77
  type: ss
- name: 美国-2
  network: ws
  port: 80
  server: visa.org
  servername: csgo.mozilla.5.0.xn--2b5baaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.127.0.0.1.offlinespeedtest.netdown.user.xn--2b5baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.0.2.1.xn--j9h1028mqmaoytii00aha21hfjrd.xn--m39h.tor.rubika.cloudns.ch.
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 071adfc4-b337-4a90-bdcc-e66a4d327c55
  ws-opts:
    headers:
      Host: csgo.mozilla.5.0.xn--2b5baaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.127.0.0.1.offlinespeedtest.netdown.user.xn--2b5baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.0.2.1.xn--j9h1028mqmaoytii00aha21hfjrd.xn--m39h.tor.rubika.cloudns.ch.
    path: /xmlrpc.php?ed=1080
- client-fingerprint: chrome
  name: 美国-3
  network: ws
  port: 80
  server: 199.232.8.123
  servername: IRANINGOAT2.IR
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: d578322a-266b-479d-9eda-f1b41324e721
  ws-opts:
    headers:
      Host: IRANINGOAT2.IR
    path: /RsAMasAPMX5yb1YZ?ed=2560fp=chrome
- client-fingerprint: chrome
  name: 美国-4
  network: ws
  port: 80
  server: 199.232.8.123
  servername: IRANINGOAT2.IR
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: d578322a-266b-479d-9eda-f1b41324e721
  ws-opts:
    headers:
      Host: IRANINGOAT2.IR
    path: /RsAMasAPMX5yb1YZ?ed=2560fp=chromefp=chrome
- name: 美国-5
  network: ws
  port: 80
  server: 104.18.165.30
  servername: csgo.mozilla.5.0.xn--2b5baaa.127.0.0.1.offlinespeedtest.netdown.user.xn--2b5baaa.0.2.1.xn--j9h1028mqmaoytii00aha21hfjrd.xn--m39h.ajab.iP-ddns.com.
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 19d13bed-b8c5-4443-920e-12f833fed576
  ws-opts:
    headers:
      Host: csgo.mozilla.5.0.xn--2b5baaa.127.0.0.1.offlinespeedtest.netdown.user.xn--2b5baaa.0.2.1.xn--j9h1028mqmaoytii00aha21hfjrd.xn--m39h.ajab.iP-ddns.com.
    path: /xmlrpc.php/Telegram,VPNCUSTOMIZE,Telegram,VPNCUSTOMIZE,Telegram,VPNCUSTOMIZE?ed=1080
- cipher: rc4-md5
  name: 美国-6
  password: 14fFPrbezE3HDZzsMOr6
  port: 8080
  server: 107.155.57.11
  type: ss
  udp: true
- name: 美国-7
  password: f0eb8c92ce8946aaba856569cff1a16b
  port: 443
  server: 142.202.48.220
  skip-cert-verify: true
  sni: sherasheba.com
  type: trojan
- name: 美国-8
  password: 0ab6c98dae3b48e8b9c4a776b6c9c19a
  port: 443
  server: sherasheba.com
  skip-cert-verify: true
  type: trojan
  udp: true
- name: 美国-9
  password: f0eb8c92ce8946aaba856569cff1a16b
  port: 443
  server: sherasheba.com
  skip-cert-verify: true
  type: trojan
  udp: true
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 41个'
  - '自动选择(国内): 10个'
  - '自动选择(国外): 31个'
  - '手动选择: 41个'
  - '中国分区: 1个'
  - '英国分区: 1个'
  - '香港分区: 9个'
  - '哈萨克斯坦分区: 1个'
  - '拉脱维亚分区: 1个'
  - '荷兰分区: 1个'
  - '波兰分区: 16个'
  - '新加坡分区: 2个'
  - '美国分区: 9个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 41个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 10个'
  proxies:
  - 中国-1
  - 香港-1
  - 香港-2
  - 香港-3
  - 香港-4
  - 香港-5
  - 香港-6
  - 香港-7
  - 香港-8
  - 香港-9
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 31个'
  proxies:
  - 英国-1
  - 哈萨克斯坦-1
  - 拉脱维亚-1
  - 荷兰-1
  - 波兰-1
  - 波兰-2
  - 波兰-3
  - 波兰-4
  - 波兰-5
  - 波兰-6
  - 波兰-7
  - 波兰-8
  - 波兰-9
  - 波兰-10
  - 波兰-11
  - 波兰-12
  - 波兰-13
  - 波兰-14
  - 波兰-15
  - 波兰-16
  - 新加坡-1
  - 新加坡-2
  - 美国-1
  - 美国-2
  - 美国-3
  - 美国-4
  - 美国-5
  - 美国-6
  - 美国-7
  - 美国-8
  - 美国-9
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 41个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)英国|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '英国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 9个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)哈萨克斯坦|KZ|kz
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kz.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '哈萨克斯坦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)拉脱维亚|LV|lv
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/lv.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '拉脱维亚分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)波兰|PL|pl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '波兰分区: 16个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)新加坡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '新加坡分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 9个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
