allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: chacha20-ietf-poly1305
  name: 中国-1
  password: 75393bce-9f1d-4263-98f0-27bf0f640a77
  port: 35635
  server: jsyd.yeahfast.com
  type: ss
- name: 中国-2
  password: 60849177-99ec-3fba-9615-c8de9e254409
  port: 20309
  server: gyl.58n.net
  skip-cert-verify: true
  sni: z309.hongkongnode.top
  type: trojan
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-3
  password: 75393bce-9f1d-4263-98f0-27bf0f640a77
  port: 35632
  server: jsyd.yeahfast.com
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-4
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31640
  server: jsyd.yunnode.win
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-5
  password: 75393bce-9f1d-4263-98f0-27bf0f640a77
  port: 35637
  server: jsyd.yeahfast.com
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-6
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31738
  server: jsyd.yunnode.win
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-7
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31632
  server: jsyd.yunnode.win
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-8
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31672
  server: jsyd.yunnode.win
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-9
  password: 75393bce-9f1d-4263-98f0-27bf0f640a77
  port: 35630
  server: jsyd.yeahfast.com
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-10
  password: 75393bce-9f1d-4263-98f0-27bf0f640a77
  port: 35627
  server: jsyd.yeahfast.com
  type: ss
- name: 中国-11
  password: QwwHvrnN
  port: 44673
  server: 36.151.192.203
  skip-cert-verify: true
  sni: 36.151.192.203
  type: trojan
- cipher: chacha20-ietf-poly1305
  name: 中国-12
  password: 671d1256-bf77-446c-9f43-acd17ef2d1c6
  port: 30003
  server: gdgs.tarioblink.me
  type: ss
  udp: true
- name: 中国-13
  password: QwwHvrnN
  port: 44673
  server: 36.151.192.203
  skip-cert-verify: true
  type: trojan
  udp: true
- cipher: chacha20-ietf-poly1305
  name: 中国-14
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31650
  server: jsyd.yunnode.win
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-15
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31642
  server: jsyd.yunnode.win
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-16
  password: 75393bce-9f1d-4263-98f0-27bf0f640a77
  port: 35532
  server: jsyd.yeahfast.com
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-17
  password: d3571b43-f940-410c-bf6b-f35d2db19a17
  port: 31648
  server: jsyd.yunnode.win
  type: ss
- name: 德国-1
  network: tcp
  port: 13239
  server: 91.107.248.14
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: bf61aa2e-5b05-478e-8e1e-453d27c52107
- name: 日本-1
  password: dfe1ef9b-e590-3b93-816a-e58a908bce99
  port: 443
  server: 18.179.44.127
  skip-cert-verify: true
  sni: upos-hz-mirrorakam.akamaized.net
  type: trojan
  udp: true
- name: 美国-1
  password: dfe1ef9b-e590-3b93-816a-e58a908bce99
  port: 3516
  server: 103.136.185.28
  skip-cert-verify: true
  sni: origin-a.akamaihd.net
  type: trojan
  udp: true
- name: 美国-2
  network: ws
  port: 443
  server: 172.66.44.237
  servername: pardazeshvpn-tg85.pages.dev
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 76434743-2a94-4cfd-8170-8e3971419b36
  ws-opts:
    headers:
      Host: pardazeshvpn-tg85.pages.dev
    path: '/Telegram:'
- alterId: 0
  cipher: auto
  name: 美国-3
  network: ws
  port: 2095
  server: 172.64.167.29
  servername: c3.6016725.xyz
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: 18d96190-c10f-448f-a82a-2d36df5c3cde
  ws-opts:
    headers:
      Host: c3.6016725.xyz
    path: /github.com/Alvin9999
- name: 美国-4
  network: ws
  port: 443
  server: lix523052.filegear-sg.me
  servername: lix523052.filegear-sg.me
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: e6259fa3-fb06-4f9b-ad3f-bd6250b837f6
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 美国-5
  network: ws
  port: 2095
  server: 172.64.166.28
  servername: c3.6016725.xyz
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: 18d96190-c10f-448f-a82a-2d36df5c3cde
  ws-opts:
    headers:
      Host: c3.6016725.xyz
    path: /github.com/Alvin9999
- alterId: 0
  cipher: auto
  name: 美国-6
  network: ws
  port: 2095
  server: 172.64.198.249
  servername: c3.6016725.xyz
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: 18d96190-c10f-448f-a82a-2d36df5c3cde
  ws-opts:
    headers:
      Host: c3.6016725.xyz
    path: /github.com/Alvin9999
- name: 美国-7
  network: ws
  port: 443
  server: 172.66.47.19
  servername: pardazeshvpn-tg85.pages.dev
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 76434743-2a94-4cfd-8170-8e3971419b36
  ws-opts:
    headers:
      Host: pardazeshvpn-tg85.pages.dev
    path: '/Telegram:'
- alterId: 0
  cipher: auto
  name: 美国-8
  network: ws
  port: 2095
  server: 172.64.167.22
  servername: c3.6016725.xyz
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: 18d96190-c10f-448f-a82a-2d36df5c3cde
  ws-opts:
    headers:
      Host: c3.6016725.xyz
    path: /github.com/Alvin9999
- name: 美国-9
  network: ws
  password: WOeXShhJpL
  port: 443
  server: 104.17.8.124
  skip-cert-verify: true
  sni: 10jzus.zdzdzd.xyz
  type: trojan
  ws-opts:
    headers:
      Host: 10jzus.zdzdzd.xyz
    path: /juzigongyi
- name: 美国-10
  network: ws
  password: WOeXShhJpL
  port: 443
  server: 172.67.232.40
  skip-cert-verify: true
  sni: 10jzus.zdzdzd.xyz
  type: trojan
  ws-opts:
    headers:
      Host: 10jzus.zdzdzd.xyz
    path: /juzigongyi
- alterId: 0
  cipher: auto
  name: 美国-11
  network: ws
  port: 2095
  server: 172.64.167.44
  servername: c3.6016725.xyz
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: 18d96190-c10f-448f-a82a-2d36df5c3cde
  ws-opts:
    headers:
      Host: c3.6016725.xyz
    path: /github.com/Alvin9999
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 30个'
  - '自动选择(国内): 17个'
  - '自动选择(国外): 13个'
  - '手动选择: 30个'
  - '中国分区: 17个'
  - '德国分区: 1个'
  - '日本分区: 1个'
  - '美国分区: 11个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 30个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 17个'
  proxies:
  - 中国-1
  - 中国-2
  - 中国-3
  - 中国-4
  - 中国-5
  - 中国-6
  - 中国-7
  - 中国-8
  - 中国-9
  - 中国-10
  - 中国-11
  - 中国-12
  - 中国-13
  - 中国-14
  - 中国-15
  - 中国-16
  - 中国-17
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 13个'
  proxies:
  - 德国-1
  - 日本-1
  - 美国-1
  - 美国-2
  - 美国-3
  - 美国-4
  - 美国-5
  - 美国-6
  - 美国-7
  - 美国-8
  - 美国-9
  - 美国-10
  - 美国-11
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 30个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 17个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)日本|JP|jp
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/jp.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '日本分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 11个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
