allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- name: 中国-1
  password: QwwHvrnN
  port: 42395
  server: 36.151.192.239
  skip-cert-verify: true
  type: trojan
  udp: true
- alterId: 64
  cipher: auto
  name: 中国-2
  port: 42055
  server: 120.198.71.219
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 中国-3
  port: 54104
  server: 183.236.51.23
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 中国-4
  port: 56601
  server: 183.236.51.23
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- alterId: 64
  cipher: auto
  name: 中国-5
  port: 40434
  server: 183.236.51.23
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
- name: 德国-1
  network: ws
  port: 443
  server: 193.122.58.158
  servername: de.bolagskontaktstockholm.se
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 1aae9657-c653-495d-e8ad-8ca52916cea8
  ws-opts:
    headers:
      Host: de.bolagskontaktstockholm.se
    path: /ws
- name: 德国-2
  network: ws
  port: 443
  server: 212.224.93.93
  servername: blog.codegethub.org
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: 14ba4514-3846-45c0-aec6-444e5451b95c
  ws-opts:
    headers:
      Host: blog.codegethub.org
    path: /ws@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel----@PersiaTM_Channel
- name: 芬兰-1
  network: ws
  port: 45493
  server: 37.27.220.2
  servername: torob.com
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 4bc75123-5ca4-45c7-9206-6151490879d7
  ws-opts:
    headers:
      Host: torob.com
    path: /roshd
- alterId: 0
  cipher: auto
  http-opts:
    method: GET
    path:
    - /
  name: 香港-1
  network: http
  port: 35384
  server: 45.94.68.206
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: b3e95701-dbd0-4a2f-a701-6ec815fb5ad2
- name: 英国-1
  password: 984e400bf5d541b7b0815913fe0c432a
  port: 443
  server: 172.99.190.180
  skip-cert-verify: true
  sni: bangladeshipatri.com
  type: trojan
- name: 英国-2
  password: 4732adfa16c6450bbef87264e41332db
  port: 443
  server: 172.99.190.180
  skip-cert-verify: true
  sni: bangladeshipatri.com
  type: trojan
- name: 香港-2
  port: 4000
  server: ftq.ink
  tls: true
  type: http
- name: 香港-3
  port: 4000
  server: hk9.ftq.ink
  tls: true
  type: http
- cipher: chacha20-ietf-poly1305
  name: 荷兰-1
  password: nq96KftrZAj3LuFQESqmn44Mo5oCuo2cipoEsae25mrmHG2oJ4VT37scBfVBpN5DWtUELZutVhhXs8Le5B8fZ9hLn9ytwvbf
  port: 42501
  server: 208.67.105.87
  type: ss
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-1
  network: ws
  port: 5743
  server: 195.58.49.50
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 3968cc63-8126-49d6-a7c2-14f119fa8182
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-2
  network: ws
  port: 5743
  server: 194.87.69.52
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 3968cc63-8126-49d6-a7c2-14f119fa8182
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-3
  network: ws
  port: 5743
  server: 195.58.49.86
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 3968cc63-8126-49d6-a7c2-14f119fa8182
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-4
  network: ws
  port: 16712
  server: 195.58.49.42
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 3968cc63-8126-49d6-a7c2-14f119fa8182
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-5
  network: ws
  port: 5743
  server: 194.87.69.50
  skip-cert-verify: false
  tls: false
  type: vmess
  uuid: 3968cc63-8126-49d6-a7c2-14f119fa8182
  ws-opts:
    path: /
- alterId: 0
  cipher: auto
  name: 俄罗斯联邦-6
  network: ws
  port: 16712
  server: 195.58.49.42
  skip-cert-verify: true
  tls: false
  type: vmess
  uuid: 1ded1ec9-7557-4c15-aaac-758bedea64fd
  ws-opts:
    path: /
- name: 新加坡-1
  password: 0ab6c98dae3b48e8b9c4a776b6c9c19a
  port: 443
  server: connectwithemployers.online
  skip-cert-verify: false
  type: trojan
- name: 新加坡-2
  password: 0ab6c98dae3b48e8b9c4a776b6c9c19a
  port: 443
  server: 139.59.119.143
  skip-cert-verify: true
  sni: connectwithemployers.online
  type: trojan
- alterId: 0
  cipher: auto
  name: 美国-1
  network: ws
  port: 8049
  server: us.aik.mom
  skip-cert-verify: false
  tls: false
  type: vmess
  udp: true
  uuid: 15486dcc-f6e5-411b-acac-d1409375585a
  ws-opts:
    headers:
      Host: tms.dingtalk.com
    path: /wada12222
- name: 越南-1
  password: 25a0ffa0-725c-4d6f-b0d5-c74579753075
  port: 443
  server: Cmc3.5gsieuvip.vn
  skip-cert-verify: true
  type: trojan
  udp: true
- name: 越南-2
  password: 25a0ffa0-725c-4d6f-b0d5-c74579753075
  port: 443
  server: cmc3.5gsieuvip.vn
  skip-cert-verify: true
  type: trojan
  udp: true
- name: 越南-3
  password: 25a0ffa0-725c-4d6f-b0d5-c74579753075
  port: 443
  server: 103.173.66.155
  skip-cert-verify: true
  type: trojan
  udp: true
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 26个'
  - '自动选择(国内): 8个'
  - '自动选择(国外): 18个'
  - '手动选择: 26个'
  - '中国分区: 5个'
  - '德国分区: 2个'
  - '芬兰分区: 1个'
  - '香港分区: 3个'
  - '英国分区: 2个'
  - '荷兰分区: 1个'
  - '俄罗斯联邦分区: 6个'
  - '新加坡分区: 2个'
  - '美国分区: 1个'
  - '越南分区: 3个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 26个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 8个'
  proxies:
  - 中国-1
  - 中国-2
  - 中国-3
  - 中国-4
  - 中国-5
  - 香港-1
  - 香港-2
  - 香港-3
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 18个'
  proxies:
  - 德国-1
  - 德国-2
  - 芬兰-1
  - 英国-1
  - 英国-2
  - 荷兰-1
  - 俄罗斯联邦-1
  - 俄罗斯联邦-2
  - 俄罗斯联邦-3
  - 俄罗斯联邦-4
  - 俄罗斯联邦-5
  - 俄罗斯联邦-6
  - 新加坡-1
  - 新加坡-2
  - 美国-1
  - 越南-1
  - 越南-2
  - 越南-3
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 26个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 5个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)德国|DE|de
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/de.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '德国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)芬兰|FI|fi
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/fi.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '芬兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)香港|HK|hk
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/hk.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '香港分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)英国|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '英国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)俄罗斯联邦|RU|ru
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/ru.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '俄罗斯联邦分区: 6个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)新加坡|SG|sg
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/sg.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '新加坡分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)美国|US|us
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/us.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '美国分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)越南|VN|vn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/vn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '越南分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
