allow-lan: false
dns:
  cache-algorithm: arc
  default-nameserver:
  - 223.5.5.5
  - 114.114.114.114
  - 1.1.1.1
  - 8.8.8.8
  dns: true
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  fake-ip-range: 198.18.0.1/16
  fallback: []
  ipv6: true
  listen: 1053
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  nameserver-policy:
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://194.242.2.2/dns-query
    - https://194.242.2.3/dns-query
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
  proxy-server-nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  - https://doh.360.cn/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://194.242.2.2/dns-query
  - https://194.242.2.3/dns-query
  use-system-hosts: false
external-controller: 127.0.0.1:9097
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
find-process-mode: strict
geodata-mode: true
geox-url:
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
global-client-fingerprint: chrome
ipv6: true
log-level: info
mixed-port: 7897
mode: rule
port: 7899
profile:
  store-fake-ip: true
  store-selected: true
proxies:
- cipher: chacha20-ietf-poly1305
  name: 中国-1
  password: f5136746-de79-46d0-b3be-d15d9992fa07
  port: 32481
  server: zx2.1010520.xyz
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-2
  password: f5136746-de79-46d0-b3be-d15d9992fa07
  port: 26415
  server: zx3.1010520.xyz
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-3
  password: f5136746-de79-46d0-b3be-d15d9992fa07
  port: 26415
  server: zx2.1010520.xyz
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 中国-4
  password: f5136746-de79-46d0-b3be-d15d9992fa07
  port: 32481
  server: zx1.1010520.xyz
  type: ss
- name: 捷克-1
  network: ws
  port: 8000
  server: 194.87.11.56
  servername: a.mifeng.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: a.mifeng.us.kg
    path: /?ed=2560
- name: 西班牙-1
  network: ws
  port: 8080
  server: 94.250.246.200
  servername: a.mifeng.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: a.mifeng.us.kg
    path: /?ed=2560
- cipher: aes-128-gcm
  name: 英国-1
  password: shadowsocks
  port: 443
  server: 212.102.53.193
  type: ss
- name: 英国-2
  network: ws
  port: 587
  server: 8.208.94.35
  servername: a.mifeng.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: a.mifeng.us.kg
    path: /?ed=2560
- cipher: aes-256-cfb
  name: 韩国-1
  password: qwerREWQ@@
  port: 21215
  server: p228.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-2
  password: qwerREWQ@@
  port: 41748
  server: p230.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-3
  password: qwerREWQ@@
  port: 33551
  server: p227.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-4
  password: qwerREWQ@@
  port: 41105
  server: 221.150.109.21
  type: ss
- cipher: aes-256-cfb
  name: 韩国-5
  password: qwerREWQ@@
  port: 33551
  server: 125.141.26.12
  type: ss
- cipher: aes-256-cfb
  name: 韩国-6
  password: qwerREWQ@@
  port: 59974
  server: 210.217.18.69
  type: ss
- cipher: aes-256-cfb
  name: 韩国-7
  password: qwerREWQ@@
  port: 3231
  server: p239.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-8
  password: qwerREWQ@@
  port: 51219
  server: 125.141.31.103
  type: ss
- cipher: aes-256-cfb
  name: 韩国-9
  password: qwerREWQ@@
  port: 40244
  server: 125.141.26.14
  type: ss
- cipher: aes-256-cfb
  name: 韩国-10
  password: qwerREWQ@@
  port: 40244
  server: p229.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-11
  password: qwerREWQ@@
  port: 57884
  server: 125.141.31.72
  type: ss
- name: 韩国-12
  network: ws
  port: 587
  server: 140.238.2.81
  servername: a.mifeng.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: a.mifeng.us.kg
    path: /?ed=2560
- cipher: aes-256-cfb
  name: 韩国-13
  password: qwerREWQ@@
  port: 3231
  server: 210.217.18.70
  type: ss
- cipher: aes-256-cfb
  name: 韩国-14
  password: qwerREWQ@@
  port: 19533
  server: 203.234.238.140
  type: ss
- cipher: aes-256-cfb
  name: 韩国-15
  password: qwerREWQ@@
  port: 41105
  server: p238.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-16
  password: qwerREWQ@@
  port: 41748
  server: 221.150.109.90
  type: ss
- cipher: aes-256-cfb
  name: 韩国-17
  password: qwerREWQ@@
  port: 40915
  server: 168.126.234.233
  type: ss
- cipher: aes-256-cfb
  name: 韩国-18
  password: qwerREWQ@@
  port: 59974
  server: p241.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-19
  password: qwerREWQ@@
  port: 43249
  server: p234.panda004.net
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 韩国-20
  password: qwerREWQ@@
  port: 25415
  server: 168.126.234.232
  type: ss
- cipher: aes-256-cfb
  name: 韩国-21
  password: qwerREWQ@@
  port: 43249
  server: 222.112.15.140
  type: ss
- cipher: aes-256-cfb
  name: 韩国-22
  password: qwerREWQ@@
  port: 25730
  server: 168.126.234.230
  type: ss
- cipher: aes-256-cfb
  name: 韩国-23
  password: amazonskr05
  port: 443
  server: 52.79.248.193
  type: ss
- cipher: chacha20-ietf-poly1305
  name: 哈萨克斯坦-1
  password: 3N2JoZhDodMX5wPfr0xbT5
  port: 52839
  server: 45.8.98.163
  type: ss
- client-fingerprint: chrome
  name: 荷兰-1
  network: ws
  port: 7000
  server: 5.2.73.137
  servername: a.mifeng.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: a.mifeng.us.kg
    path: /?ed=2560
- name: 荷兰-2
  port: 2198
  server: 185.236.233.136
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 838f5273-5d2d-4630-a0f5-9cc8e4aef4d6
- http-opts:
    headers:
      Host:
      - Speedtest.net
    method: GET
    path:
    - /
  name: 荷兰-3
  network: http
  port: 23701
  server: 146.190.16.108
  servername: Speedtest.net
  skip-cert-verify: false
  tls: false
  type: vless
  uuid: 677a41e5-dbe6-429b-8f91-cc014b1ae1bd
- cipher: aes-256-cfb
  name: 波兰-1
  password: f63gg8EruDnUrmz4
  port: 9010
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-2
  password: XPtzA9sCug3SPR4c
  port: 9025
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-3
  password: BejrQvtu9sqUeNuZ
  port: 9024
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-4
  password: GA9KzeEgvfxNrgmM
  port: 9019
  server: 217.30.10.18
  type: ss
- cipher: aes-256-cfb
  name: 波兰-5
  password: f8npKgNzdkss2ytn
  port: 9088
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-6
  password: TPqX8edgbAURcAMb
  port: 9079
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-7
  password: c3NtHJ5ujV2tGDfj
  port: 9084
  server: 217.30.10.18
  type: ss
- cipher: aes-256-cfb
  name: 波兰-8
  password: EXN3S3eQpjE7EJu8
  port: 9027
  server: 217.30.10.18
  type: ss
  udp: true
- cipher: aes-256-cfb
  name: 波兰-9
  password: cp8pRSUAyLhTfVWH
  port: 9064
  server: 217.30.10.18
  type: ss
  udp: true
- name: 瑞典-1
  network: ws
  port: 2501
  server: 95.164.51.24
  servername: a.mifeng.us.kg
  skip-cert-verify: false
  tls: true
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
  ws-opts:
    headers:
      Host: a.mifeng.us.kg
    path: /?ed=2560
- cipher: aes-256-cfb
  name: 台湾-1
  password: qwerREWQ@@
  port: 64759
  server: 185.189.160.98
  type: ss
proxy-groups:
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Final.png
  name: 默认代理
  proxies:
  - '自动选择: 46个'
  - '自动选择(国内): 4个'
  - '自动选择(国外): 42个'
  - '手动选择: 46个'
  - '中国分区: 4个'
  - '捷克分区: 1个'
  - '西班牙分区: 1个'
  - '英国分区: 2个'
  - '韩国分区: 23个'
  - '哈萨克斯坦分区: 1个'
  - '荷兰分区: 3个'
  - '波兰分区: 9个'
  - '瑞典分区: 1个'
  - '台湾分区: 1个'
  type: select
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择: 46个'
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国内): 4个'
  proxies:
  - 中国-1
  - 中国-2
  - 中国-3
  - 中国-4
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- hidden: true
  icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Auto.png
  include-all-providers: false
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '自动选择(国外): 42个'
  proxies:
  - 捷克-1
  - 西班牙-1
  - 英国-1
  - 英国-2
  - 韩国-1
  - 韩国-2
  - 韩国-3
  - 韩国-4
  - 韩国-5
  - 韩国-6
  - 韩国-7
  - 韩国-8
  - 韩国-9
  - 韩国-10
  - 韩国-11
  - 韩国-12
  - 韩国-13
  - 韩国-14
  - 韩国-15
  - 韩国-16
  - 韩国-17
  - 韩国-18
  - 韩国-19
  - 韩国-20
  - 韩国-21
  - 韩国-22
  - 韩国-23
  - 哈萨克斯坦-1
  - 荷兰-1
  - 荷兰-2
  - 荷兰-3
  - 波兰-1
  - 波兰-2
  - 波兰-3
  - 波兰-4
  - 波兰-5
  - 波兰-6
  - 波兰-7
  - 波兰-8
  - 波兰-9
  - 瑞典-1
  - 台湾-1
  - COMPATIBLE
  timeout: 1500
  type: url-test
  url: https://www.google.com/generate_204
- icon: https://fastly.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Dark/Available.png
  include-all-proxies: true
  name: '手动选择: 46个'
  type: select
- filter: (?i)中国|CN|cn
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cn.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '中国分区: 4个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)捷克|CZ|cz
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/cz.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '捷克分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)西班牙|ES|es
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/es.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '西班牙分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)英国|GB|gb
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/gb.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '英国分区: 2个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)韩国|KR|kr
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kr.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '韩国分区: 23个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)哈萨克斯坦|KZ|kz
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/kz.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '哈萨克斯坦分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)荷兰|NL|nl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/nl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '荷兰分区: 3个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)波兰|PL|pl
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/pl.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '波兰分区: 9个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)瑞典|SE|se
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/se.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '瑞典分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
- filter: (?i)台湾|TW|tw
  hidden: false
  icon: https://fastly.jsdelivr.net/gh/clash-verge-rev/clash-verge-rev.github.io@main/docs/assets/icons/flags/tw.svg
  include-all-providers: false
  include-all-proxies: true
  interval: 300
  lazy: true
  max-failed-times: 3
  name: '台湾分区: 1个'
  proxies:
  - COMPATIBLE
  strategy: round-robin
  timeout: 1500
  type: load-balance
  url: https://www.google.com/generate_204
rules:
- GEOIP,lan,DIRECT,no-resolve
- GEOSITE,category-ads-all,REJECT
- GEOSITE,github,默认代理
- DOMAIN,cdn.usefathom.com,默认代理
- GEOSITE,anthropic,默认代理
- GEOSITE,microsoft,DIRECT
- GEOIP,google,默认代理
- GEOIP,telegram,默认代理
- GEOIP,twitter,默认代理
- GEOIP,CN,DIRECT,no-resolve
- MATCH,默认代理
secret: ''
sniffer:
  enable: true
  skip-domain:
  - +.push.apple.com
  sniff:
    HTTP:
      override-destination: true
      ports:
      - 80
      - 8080-8880
    QUIC:
      ports:
      - 443
      - 8443
    TLS:
      ports:
      - 443
      - 8443
socks-port: 7898
tcp-concurrent: true
tun:
  auto-detect-interface: true
  auto-redirect: true
  auto-route: true
  device: Meta
  dns-hijack:
  - any:53
  enable: true
  mtu: 1500
  stack: mixed
  strict-route: false
unified-delay: false
