name: 定时清理执行日志

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest

    steps:
      - name: 删除日志文件
        uses: dongchengjie/workflow-runs-cleaner@v1
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.RENAMEPROXIES }}
          maintain-span: '3d'
