name: 安装 mmdbinspect 并运行脚本

on:
  # 允许手动触发工作流
  workflow_dispatch:

  # 每隔四小时触发一次
  schedule:
    - cron: '0 */4 * * *'

jobs:
  run-script:
    # 在最新的 Ubuntu 环境下运行
    runs-on: ubuntu-latest

    steps:
      - name: Git 配置
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git config --global http.proxy  http://127.0.0.1:7890
          git config --global https.proxy http://127.0.0.1:7890

      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载 mmdbinspect
        run: |
          wget https://github.com/maxmind/mmdbinspect/releases/download/v0.2.0/mmdbinspect_0.2.0_linux_amd64.deb

      - name: 安装 mmdbinspect
        run: |
          sudo dpkg -i mmdbinspect_0.2.0_linux_amd64.deb

      - name: 运行 renameProxies.py
        run: |
          python renameProxies.py

      - name: 上传 renameProxies.yaml
        run: |
          git add renameProxies.yaml
          git commit -m "Add renameProxies.yaml"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
