name: 安装 mmdbinspect 并运行脚本

on:
  # 允许手动触发工作流
  workflow_dispatch:

  # 每隔四小时触发一次
  schedule:
    - cron: '0 */4 * * *'

jobs:
  run-script:
    # 在最新的 Ubuntu 环境下运行
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        # 使用 GitHub Actions 提供的 checkout 操作来拉取代码
        uses: actions/checkout@v4

      - name: 下载 mmdbinspect
        # 下载 mmdbinspect 的 Debian 安装包
        run: |
          wget https://github.com/maxmind/mmdbinspect/releases/download/v0.2.0/mmdbinspect_0.2.0_linux_amd64.deb

      - name: 安装 mmdbinspect
        # 安装 mmdbinspect
        run: |
          sudo dpkg -i mmdbinspect_0.2.0_linux_amd64.deb

      - name: 运行 renameProxies.py
        # 执行 renameProxies.py 脚本
        run: |
          python renameProxies.py

      - name: 上传 renameProxies.yaml
        # 将生成的 renameProxies.yaml 文件上传到 GitHub 仓库
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-username"
          git add renameProxies.yaml
          git commit -m "Add renameProxies.yaml"
          git push
