name: 安装 mmdbinspect 并运行脚本

on:
  # 允许手动触发工作流
  workflow_dispatch:

  # 每隔四小时触发一次
  schedule:
    - cron: '0 */4 * * *'

permissions:
  contents: write

jobs:
  run-script:
    # 在最新的 Ubuntu 环境下运行
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: Git配置
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git pull
    
      - name: 下载 geoip 数据库
        run: |
          wget https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb

      - name: 下载 mmdbinspect
        run: |
          wget https://github.com/maxmind/mmdbinspect/releases/download/v0.2.0/mmdbinspect_0.2.0_linux_amd64.deb

      - name: 安装 mmdbinspect
        run: |
          sudo dpkg -i mmdbinspect_0.2.0_linux_amd64.deb

      - name: 运行 renameProxies.py
        run: |
          python renameProxies.py

      - name: 删除多余文件
        run: |
          sudo rm -f mmdbinspect_0.2.0_linux_amd64.deb
          sudo rm -f Country.mmdb

      - name: 上传 finalConfig.yaml
        run: |
          git add finalConfig.yaml
          git commit -m "update by workflows" && git push --force
